# -*- coding: utf-8 -*-
# @Time : 9/11/2023 10:42 AM
# @Author : Marvin Ma

from synnex.bigdata import conf
from synnex.bigdata.pyspark import run_sql
# dw_{country}.dws_disty_brpt_bd_vpl_comb_mtd


def main():
    country = conf.get("country")
    date_flag = conf.get("date_flag")  # date_flag = yesterday = @process_date
    dt_month = conf.get("dt_month")  # date_flag format to 'yyyy-MM'
    etl_timestamp = conf.get("etl_timestamp")

    exec_main_sql(country, date_flag, dt_month, etl_timestamp)


def exec_main_sql(country, date_flag, dt_month, etl_timestamp):
    main_sql = r"""
    insert overwrite table dw_{country}.dws_disty_brpt_bd_vend_comb_mtd partition(date_flag = '{date_flag}')
    select
        month_no,
        project_no,
        project_name,
        task_no,
        task_name,
        company_no,
        vend_no,
        vend_name,
        master_vend_no,
        master_vend_name,
        seg_code,

        sum(d_sales),
        sum(d_cost),
        sum(d_unit),
        sum(d_gm),
        sum(d_ngm),
        sum(d_opl),
        sum(d_scm_usage),
        sum(d_tgm),
        sum(d_cgp),
        sum(d_total_btl),
        sum(w_sales),
        sum(w_cost),
        sum(w_unit),
        sum(w_gm),
        sum(w_ngm),
        sum(w_opl),
        sum(w_scm_usage),
        sum(w_tgm),
        sum(w_cgp),
        sum(w_total_btl),
        sum(m_sales),
        sum(m_cost),
        sum(m_unit),
        sum(m_gm),
        sum(m_ngm),
        sum(m_opl),
        sum(m_scm_usage),
        sum(m_tgm),
        sum(m_scm_disc),
        sum(m_scm_ndisc),
        sum(m_ds_sales),
        sum(m_stock_sales),
        sum(m_ds_cost),
        sum(m_stock_cost),
        sum(m_ds_scm_usage),
        sum(m_stock_scm_usage),
        sum(m_cgp),
        sum(m_total_btl),
        sum(pm_sales),
        sum(pm_cost),
        sum(pm_unit),
        sum(pm_gm),
        sum(pm_ngm),
        sum(pm_opl),
        sum(pm_scm_usage),
        sum(pm_tgm),
        sum(pm_scm_disc),
        sum(pm_scm_ndisc),
        sum(pm_ds_sales),
        sum(pm_stock_sales),
        sum(pm_ds_cost),
        sum(pm_stock_cost),
        sum(pm_ds_scm_usage),
        sum(pm_stock_scm_usage),
        sum(pm_cgp),
        sum(pm_total_btl),
        sum(ppm_sales),
        sum(ppm_cost),
        sum(ppm_unit),
        sum(ppm_gm),
        sum(ppm_ngm),
        sum(ppm_opl),
        sum(ppm_scm_usage),
        sum(ppm_tgm),
        sum(ppm_scm_disc),
        sum(ppm_scm_ndisc),
        sum(ppm_ds_sales),
        sum(ppm_stock_sales),
        sum(ppm_ds_cost),
        sum(ppm_stock_cost),
        sum(ppm_ds_scm_usage),
        sum(ppm_stock_scm_usage),
        sum(ppm_cgp),
        sum(ppm_total_btl),
        sum(lm_sales),
        sum(lm_cost),
        sum(lm_unit),
        sum(lm_gm),
        sum(lm_ngm),
        sum(lm_opl),
        sum(lm_scm_usage),
        sum(lm_tgm),
        sum(lm_scm_disc),
        sum(lm_scm_ndisc),
        sum(lm_ds_sales),
        sum(lm_stock_sales),
        sum(lm_ds_cost),
        sum(lm_stock_cost),
        sum(lm_ds_scm_usage),
        sum(lm_stock_scm_usage),
        sum(lm_cgp),
        sum(lm_total_btl),

        sum(bo_gross_sales),
        sum(bo_gross_cost),
        sum(bo_total_unit),
        sum(bo_gm_amt),
        sum(so_gross_sales),
        sum(so_gross_cost),
        sum(so_total_unit),
        sum(so_gm_amt),
        sum(bo_age0_7),
        sum(bo_age8_14),
        sum(bo_age15_21),
        sum(bo_age21_up),
        sum(so_age0_7),
        sum(so_age8_14),
        sum(so_age15_21),
        sum(so_age21_up),

        sum(rr_unit),
        sum(rr_sales),
        sum(rr_cost),
        sum(rr_gm),
        sum(rr_ngm),
        sum(rr_opl),
        sum(rr_cgp),
        sum(rr_total_btl),
        sum(rr_tgm),
        '{etl_timestamp}',
        b33_flag,
        sum(d_fx_cost),
        sum(w_fx_cost),
        sum(m_fx_cost),
        sum(pm_fx_cost),
        sum(ppm_fx_cost),
        sum(lm_fx_cost),
        
        sum(d_oplgm_plus_amt  ),
        sum(w_oplgm_plus_amt  ),
        sum(m_oplgm_plus_amt  ),
        sum(pm_oplgm_plus_amt ),
        sum(ppm_oplgm_plus_amt),
        sum(lm_oplgm_plus_amt ),
        sum(rr_oplgm_plus_amt )
    from dw_{country}.dws_disty_brpt_bd_vpl_comb_mtd
    where date_flag = '{date_flag}'
    group by
        month_no,
        project_no,
        project_name,
        task_no,
        task_name,
        b33_flag,
        company_no,
        vend_no,
        vend_name,
        master_vend_no,
        master_vend_name,
        seg_code
    """.format(country=country, date_flag=date_flag, dt_month=dt_month, etl_timestamp=etl_timestamp)
    run_sql(main_sql)


main()