# -*- coding: utf-8 -*-
# @Time : 9/20/2023 3:25 PM
# @Author : Marvin Ma

from synnex.bigdata import conf
from synnex.bigdata.pyspark import run_sql

# dw_{country}.dws_disty_brpt_part_comb_mtd
# ods_{country}.ods_cis_corp_manager
#
# dws_disty_brpt_vpl_comb_mtd
# dim_pub_vpl_hierarchy_info_df


def main():
    country = conf.get("country")
    date_flag = conf.get("date_flag")  # date_flag = yesterday = @process_date
    dt_month = conf.get("dt_month")  # date_flag format to 'yyyy-MM'
    etl_timestamp = conf.get("etl_timestamp")

    exec_main_sql(country, date_flag, dt_month, etl_timestamp)
    exec_newest_hierarchy(country, date_flag, dt_month)


def exec_main_sql(country, date_flag, dt_month, etl_timestamp):
    run_sql("""
    with
    table_goal as (
    select
        seg_code,
        vp,
        director,
        manager,
        pm,
        company_no,
        sum(net_sales_local_currency)               as goal_nsales,
        sum(gm * net_sales_local_currency / 100)    as goal_gm,
        sum(ngm * net_sales_local_currency / 100)   as goal_ngm,
        null                                        as goal_opl_gm,
        null                                        as goal_oplgm_plus_amt,
        sum(tgm * net_sales_local_currency / 100)   as goal_tgm,
        sum(  nvl(dos_local_currency,0) )           as goal_dos,
        sum(pdt * net_sales_local_currency / 100)   as goal_pdt,
        sum(btl * net_sales_local_currency / 100)   as goal_total_btl
    from dw_${country}.dwd_disty_pm_report_goal_view --unique id : period + seg_code + vp + director + manager + pm + vend_no + vpl_no
    where period = ${month_no}
    and vend_no = 0
    and vpl_no = 0
    and pm <> 0
    group by 
        seg_code,
        vp,
        director,
        manager,
        pm,
        company_no
    having goal_nsales <> 0),
    
    table_dws as (
    select
        pm_id,
        pm_mgr_id,
        pm_dir_id,
        pm_vp_id,
        seg_code,
        nvl(company_no,1) as company_no,
    
        sum(d_sales) as d_sales,
        sum(d_cost) as d_cost,
        sum(d_unit) as d_unit,
        sum(d_gm) as d_gm,
        sum(d_ngm) as d_ngm,
        sum(d_opl) as d_opl,
        sum(d_oplgm_plus_amt) as d_oplgm_plus_amt,
        sum(d_scm_usage) as d_scm_usage,
        sum(d_tgm) as d_tgm,
        sum(d_cgp) as d_cgp,
        sum(d_total_btl) as d_total_btl,

        sum(w_sales) as w_sales,
        sum(w_cost) as w_cost,
        sum(w_unit) as w_unit,
        sum(w_gm) as w_gm,
        sum(w_ngm) as w_ngm,
        sum(w_opl) as w_opl,
        sum(w_oplgm_plus_amt) as w_oplgm_plus_amt,
        sum(w_scm_usage) as w_scm_usage,
        sum(w_tgm) as w_tgm,
        sum(w_cgp) as w_cgp,
        sum(w_total_btl) as w_total_btl,

        sum(m_sales) as m_sales,
        sum(m_cost) as m_cost,
        sum(m_unit) as m_unit,
        sum(m_gm) as m_gm,
        sum(m_ngm) as m_ngm,
        sum(m_opl) as m_opl,
        sum(m_oplgm_plus_amt) as m_oplgm_plus_amt,
        sum(m_scm_usage) as m_scm_usage,
        sum(m_tgm) as m_tgm,
        sum(m_scm_disc) as m_scm_disc,
        sum(m_scm_ndisc) as m_scm_ndisc,
        sum(m_ds_sales) as m_ds_sales,
        sum(m_stock_sales) as m_stock_sales,
        sum(m_ds_cost) as m_ds_cost,
        sum(m_stock_cost) as m_stock_cost,
        sum(m_ds_scm_usage) as m_ds_scm_usage,
        sum(m_stock_scm_usage) as m_stock_scm_usage,
        sum(m_cgp) as m_cgp,
        sum(m_total_btl) as m_total_btl,

        sum(pm_sales) as pm_sales,
        sum(pm_cost) as pm_cost,
        sum(pm_unit) as pm_unit,
        sum(pm_gm) as pm_gm,
        sum(pm_ngm) as pm_ngm,
        sum(pm_opl) as pm_opl,
        sum(pm_oplgm_plus_amt) as pm_oplgm_plus_amt,
        sum(pm_scm_usage) as pm_scm_usage,
        sum(pm_tgm) as pm_tgm,
        sum(pm_scm_disc) as pm_scm_disc,
        sum(pm_scm_ndisc) as pm_scm_ndisc,
        sum(pm_ds_sales) as pm_ds_sales,
        sum(pm_stock_sales) as pm_stock_sales,
        sum(pm_ds_cost) as pm_ds_cost,
        sum(pm_stock_cost) as pm_stock_cost,
        sum(pm_ds_scm_usage) as pm_ds_scm_usage,
        sum(pm_stock_scm_usage) as pm_stock_scm_usage,
        sum(pm_cgp) as pm_cgp,
        sum(pm_total_btl) as pm_total_btl,

        sum(ppm_sales) as ppm_sales,
        sum(ppm_cost) as ppm_cost,
        sum(ppm_unit) as ppm_unit,
        sum(ppm_gm) as ppm_gm,
        sum(ppm_ngm) as ppm_ngm,
        sum(ppm_opl) as ppm_opl,
        sum(ppm_oplgm_plus_amt) as ppm_oplgm_plus_amt,
        sum(ppm_scm_usage) as ppm_scm_usage,
        sum(ppm_tgm) as ppm_tgm,
        sum(ppm_scm_disc) as ppm_scm_disc,
        sum(ppm_scm_ndisc) as ppm_scm_ndisc,
        sum(ppm_ds_sales) as ppm_ds_sales,
        sum(ppm_stock_sales) as ppm_stock_sales,
        sum(ppm_ds_cost) as ppm_ds_cost,
        sum(ppm_stock_cost) as ppm_stock_cost,
        sum(ppm_ds_scm_usage) as ppm_ds_scm_usage,
        sum(ppm_stock_scm_usage) as ppm_stock_scm_usage,
        sum(ppm_cgp) as ppm_cgp,
        sum(ppm_total_btl) as ppm_total_btl,

        sum(lm_sales) as lm_sales,
        sum(lm_cost) as lm_cost,
        sum(lm_unit) as lm_unit,
        sum(lm_gm) as lm_gm,
        sum(lm_ngm) as lm_ngm,
        sum(lm_opl) as lm_opl,
        sum(lm_oplgm_plus_amt) as lm_oplgm_plus_amt,
        sum(lm_scm_usage) as lm_scm_usage,
        sum(lm_tgm) as lm_tgm,
        sum(lm_scm_disc) as lm_scm_disc,
        sum(lm_scm_ndisc) as lm_scm_ndisc,
        sum(lm_ds_sales) as lm_ds_sales,
        sum(lm_stock_sales) as lm_stock_sales,
        sum(lm_ds_cost) as lm_ds_cost,
        sum(lm_stock_cost) as lm_stock_cost,
        sum(lm_ds_scm_usage) as lm_ds_scm_usage,
        sum(lm_stock_scm_usage) as lm_stock_scm_usage,
        sum(lm_cgp) as lm_cgp,
        sum(lm_total_btl) as lm_total_btl,

        sum(bo_gross_sales) as bo_gross_sales,
        sum(bo_gross_cost) as bo_gross_cost,
        sum(bo_total_unit) as bo_total_unit,
        sum(bo_gm_amt) as bo_gm_amt,
        sum(so_gross_sales) as so_gross_sales,
        sum(so_gross_cost) as so_gross_cost,
        sum(so_total_unit) as so_total_unit,
        sum(so_gm_amt) as so_gm_amt,
        sum(bo_age0_7) as bo_age0_7,
        sum(bo_age8_14) as bo_age8_14,
        sum(bo_age15_21) as bo_age15_21,
        sum(bo_age21_up) as bo_age21_up,
        sum(so_age0_7) as so_age0_7,
        sum(so_age8_14) as so_age8_14,
        sum(so_age15_21) as so_age15_21,
        sum(so_age21_up) as so_age21_up,

        sum(reg_inv) as reg_inv,
        sum(reg_inv_age0_30) as reg_inv_age0_30,
        sum(reg_inv_age31_60) as reg_inv_age31_60,
        sum(reg_inv_age61_90) as reg_inv_age61_90,
        sum(reg_inv_age90_up) as reg_inv_age90_up,
        sum(rma_inv) as rma_inv,
        sum(rma_inv_age0_30) as rma_inv_age0_30,
        sum(rma_inv_age31_60) as rma_inv_age31_60,
        sum(rma_inv_age61_90) as rma_inv_age61_90,
        sum(rma_inv_age90_up) as rma_inv_age90_up,
        sum(oh_cost) as oh_cost,
        sum(oo_cost) as oo_cost,
        sum(oh_qty) as oh_qty,
        sum(oo_qty) as oo_qty,

        sum(rr_unit) as rr_unit,
        sum(rr_sales) as rr_sales,
        sum(rr_cost) as rr_cost,
        sum(rr_gm) as rr_gm,
        sum(rr_ngm) as rr_ngm,
        sum(rr_opl) as rr_opl,
        sum(rr_oplgm_plus_amt) as rr_oplgm_plus_amt,
        sum(rr_cgp) as rr_cgp,
        sum(rr_total_btl) as rr_total_btl,
        sum(rr_tgm) as rr_tgm,
        sum(m_p91_cost) as m_p91_cost,
        sum(d_fx_cost) as d_fx_cost,
        sum(w_fx_cost) as w_fx_cost,
        sum(m_fx_cost) as m_fx_cost,
        sum(pm_fx_cost) as pm_fx_cost,
        sum(ppm_fx_cost) as ppm_fx_cost,
        sum(lm_fx_cost) as lm_fx_cost
    from dw_${country}.dws_disty_brpt_vpl_comb_mtd
    where date_flag = '${date_flag}'
    group by
        pm_id,
        pm_mgr_id,
        pm_dir_id,
        pm_vp_id,
        seg_code,
        nvl(company_no,1) )

    insert overwrite table dm_${country}.dm_disty_brpt_pm_comb_mtd partition(date_flag = '${date_flag}')
    select
        ${month_no},
        coalesce(table_dws.pm_id,table_goal.pm,-3),
        concat_ws(' ', table_manager.firstname, table_manager.lastname) as pm_name,
        coalesce(table_dws.pm_mgr_id,table_goal.manager,-3),
        concat_ws(' ', table_manager2.firstname, table_manager2.lastname) as pm_manager_name,
        coalesce(table_dws.pm_dir_id,table_goal.director,-3),
        concat_ws(' ', table_manager3.firstname, table_manager3.lastname) as pm_director_name,
        coalesce(table_dws.pm_vp_id,table_goal.vp,-3),
        concat_ws(' ', table_manager4.firstname, table_manager4.lastname) as pm_vp_name,
        nvl(table_dws.seg_code,table_goal.seg_code),
        coalesce(table_dws.company_no,table_goal.company_no) as company_no,
        
        table_goal.goal_nsales,
        table_goal.goal_gm,
        table_goal.goal_ngm,
        table_goal.goal_opl_gm,
        table_goal.goal_tgm,
        table_goal.goal_dos,
        table_goal.goal_pdt,
        table_goal.goal_total_btl,

        d_sales,
        d_cost,
        d_unit,
        d_gm,
        d_ngm,
        d_opl,
        d_scm_usage,
        d_tgm,
        d_cgp,
        d_total_btl,
        w_sales,
        w_cost,
        w_unit,
        w_gm,
        w_ngm,
        w_opl,
        w_scm_usage,
        w_tgm,
        w_cgp,
        w_total_btl,
        m_sales,
        m_cost,
        m_unit,
        m_gm,
        m_ngm,
        m_opl,
        m_scm_usage,
        m_tgm,
        m_scm_disc,
        m_scm_ndisc,
        m_ds_sales,
        m_stock_sales,
        m_ds_cost,
        m_stock_cost,
        m_ds_scm_usage,
        m_stock_scm_usage,
        m_cgp,
        m_total_btl,
        pm_sales,
        pm_cost,
        pm_unit,
        pm_gm,
        pm_ngm,
        pm_opl,
        pm_scm_usage,
        pm_tgm,
        pm_scm_disc,
        pm_scm_ndisc,
        pm_ds_sales,
        pm_stock_sales,
        pm_ds_cost,
        pm_stock_cost,
        pm_ds_scm_usage,
        pm_stock_scm_usage,
        pm_cgp,
        pm_total_btl,
        ppm_sales,
        ppm_cost,
        ppm_unit,
        ppm_gm,
        ppm_ngm,
        ppm_opl,
        ppm_scm_usage,
        ppm_tgm,
        ppm_scm_disc,
        ppm_scm_ndisc,
        ppm_ds_sales,
        ppm_stock_sales,
        ppm_ds_cost,
        ppm_stock_cost,
        ppm_ds_scm_usage,
        ppm_stock_scm_usage,
        ppm_cgp,
        ppm_total_btl,
        lm_sales,
        lm_cost,
        lm_unit,
        lm_gm,
        lm_ngm,
        lm_opl,
        lm_scm_usage,
        lm_tgm,
        lm_scm_disc,
        lm_scm_ndisc,
        lm_ds_sales,
        lm_stock_sales,
        lm_ds_cost,
        lm_stock_cost,
        lm_ds_scm_usage,
        lm_stock_scm_usage,
        lm_cgp,
        lm_total_btl,

        bo_gross_sales,
        bo_gross_cost,
        bo_total_unit,
        bo_gm_amt,
        so_gross_sales,
        so_gross_cost,
        so_total_unit,
        so_gm_amt,
        bo_age0_7,
        bo_age8_14,
        bo_age15_21,
        bo_age21_up,
        so_age0_7,
        so_age8_14,
        so_age15_21,
        so_age21_up,

        reg_inv,
        reg_inv_age0_30,
        reg_inv_age31_60,
        reg_inv_age61_90,
        reg_inv_age90_up,
        rma_inv,
        rma_inv_age0_30,
        rma_inv_age31_60,
        rma_inv_age61_90,
        rma_inv_age90_up,
        oh_cost,
        oo_cost,
        oh_qty,
        oo_qty,

        rr_unit,
        rr_sales,
        rr_cost,
        rr_gm,
        rr_ngm,
        rr_opl,
        rr_cgp,
        rr_total_btl,
        rr_tgm,
        '${etl_timestamp}',

        null as pm_sales_2            ,
        null as pm_cost_2             ,
        null as pm_unit_2             ,
        null as pm_gm_2               ,
        null as pm_ngm_2              ,
        null as pm_opl_2              ,
        null as pm_scm_usage_2        ,
        null as pm_tgm_2              ,
        null as pm_scm_disc_2         ,
        null as pm_scm_ndisc_2        ,
        null as pm_ds_sales_2         ,
        null as pm_stock_sales_2      ,
        null as pm_ds_cost_2          ,
        null as pm_stock_cost_2       ,
        null as pm_ds_scm_usage_2     ,
        null as pm_stock_scm_usage_2  ,
        null as pm_cgp_2              ,
        null as pm_total_btl_2        ,
        null as ppm_sales_2           ,
        null as ppm_cost_2            ,
        null as ppm_unit_2            ,
        null as ppm_gm_2              ,
        null as ppm_ngm_2             ,
        null as ppm_opl_2             ,
        null as ppm_scm_usage_2       ,
        null as ppm_tgm_2             ,
        null as ppm_scm_disc_2        ,
        null as ppm_scm_ndisc_2       ,
        null as ppm_ds_sales_2        ,
        null as ppm_stock_sales_2     ,
        null as ppm_ds_cost_2         ,
        null as ppm_stock_cost_2      ,
        null as ppm_ds_scm_usage_2    ,
        null as ppm_stock_scm_usage_2 ,
        null as ppm_cgp_2             ,
        null as ppm_total_btl_2       ,
        null as lm_sales_2            ,
        null as lm_cost_2             ,
        null as lm_unit_2             ,
        null as lm_gm_2               ,
        null as lm_ngm_2              ,
        null as lm_opl_2              ,
        null as lm_scm_usage_2        ,
        null as lm_tgm_2              ,
        null as lm_scm_disc_2         ,
        null as lm_scm_ndisc_2        ,
        null as lm_ds_sales_2         ,
        null as lm_stock_sales_2      ,
        null as lm_ds_cost_2          ,
        null as lm_stock_cost_2       ,
        null as lm_ds_scm_usage_2     ,
        null as lm_stock_scm_usage_2  ,
        null as lm_cgp_2              ,
        null as lm_total_btl_2        ,
        table_dws.m_p91_cost,
        table_dws.d_fx_cost,
        table_dws.w_fx_cost,
        table_dws.m_fx_cost,
        table_dws.pm_fx_cost,
        table_dws.ppm_fx_cost,
        table_dws.lm_fx_cost,
        table_dws.d_oplgm_plus_amt   ,
        table_dws.w_oplgm_plus_amt   ,
        table_dws.m_oplgm_plus_amt   ,
        table_dws.pm_oplgm_plus_amt  ,
        table_dws.ppm_oplgm_plus_amt ,
        table_dws.lm_oplgm_plus_amt  ,
        table_dws.rr_oplgm_plus_amt  ,
        table_goal.goal_oplgm_plus_amt
    from table_dws
    full join table_goal
    on table_dws.pm_id = table_goal.pm
    and table_dws.pm_mgr_id = table_goal.manager
    and table_dws.pm_dir_id = table_goal.director
    and table_dws.pm_vp_id = table_goal.vp
    and table_dws.seg_code = table_goal.seg_code
    and (table_dws.company_no = table_goal.company_no or table_goal.company_no = -1)
    
    left join ods_${country}.ods_cis_corp_manager as table_manager   --unique id : userid
    on nvl(table_dws.pm_id,table_goal.pm) = table_manager.userid
    left join ods_${country}.ods_cis_corp_manager as table_manager2   --unique id : userid
    on nvl(table_dws.pm_mgr_id,table_goal.manager) = table_manager2.userid
    left join ods_${country}.ods_cis_corp_manager as table_manager3   --unique id : userid
    on nvl(table_dws.pm_dir_id,table_goal.director) = table_manager3.userid
    left join ods_${country}.ods_cis_corp_manager as table_manager4   --unique id : userid
    on nvl(table_dws.pm_vp_id,table_goal.vp) = table_manager4.userid
    """)


def exec_newest_hierarchy(country, date_flag, dt_month):
    """
    非_2字段： 从业务id来看，pm想按照最新的hierarchy 看现在归属自己的vpl，在历史上数据。
    _2字段:  join 人员id，纯粹看人员id， pm1去年卖了100万 今年卖了80万， 整合成一条数据：100万、80万。
    :return:
    """
    end_day_of_last_month = conf.get("end_day_of_last_month")
    end_day_of_last_2month = conf.get("end_day_of_last_2month")
    end_day_of_same_month_of_last_year = conf.get("end_day_of_same_month_of_last_year")
    sql = """
    with
    table_last_dt_month as (
    select
    pm_id,
    pm_mgr_id,
    pm_dir_id,
    pm_vp_id,
    seg_code,
    nvl(company_no,1) as company_no,
    sum(case when date_flag = '{end_day_of_last_month}' then net_sales else 0 end) as pm_sales_2,
    sum(case when date_flag = '{end_day_of_last_month}' then net_cost else 0 end) as pm_cost_2,
    sum(case when date_flag = '{end_day_of_last_month}' then total_unit else 0 end) as pm_unit_2,
    sum(case when date_flag = '{end_day_of_last_month}' then gm_amt else 0 end) as pm_gm_2,
    sum(case when date_flag = '{end_day_of_last_month}' then ngm_amt else 0 end) as pm_ngm_2,
    sum(case when date_flag = '{end_day_of_last_month}' then oplgm_amt else 0 end) as pm_opl_2,
    sum(case when date_flag = '{end_day_of_last_month}' then scm_usage else 0 end) as pm_scm_usage_2,
    sum(case when date_flag = '{end_day_of_last_month}' then tgm_amt else 0 end) as pm_tgm_2,
    sum(case when date_flag = '{end_day_of_last_month}' then scm_disc else 0 end) as pm_scm_disc_2,
    sum(case when date_flag = '{end_day_of_last_month}' then scm_ndisc else 0 end) as pm_scm_ndisc_2,
    sum(case when date_flag = '{end_day_of_last_month}' then ds_sales else 0 end) as pm_ds_sales_2,
    sum(case when date_flag = '{end_day_of_last_month}' then stock_sales else 0 end) as pm_stock_sales_2,
    sum(case when date_flag = '{end_day_of_last_month}' then ds_cost else 0 end) as pm_ds_cost_2,
    sum(case when date_flag = '{end_day_of_last_month}' then stock_cost else 0 end) as pm_stock_cost_2,
    sum(case when date_flag = '{end_day_of_last_month}' then ds_scm_usage else 0 end) as pm_ds_scm_usage_2,
    sum(case when date_flag = '{end_day_of_last_month}' then stock_scm_usage else 0 end) as pm_stock_scm_usage_2,
    sum(case when date_flag = '{end_day_of_last_month}' then cgp else 0 end) as pm_cgp_2,
    sum(case when date_flag = '{end_day_of_last_month}' then total_btl else 0 end) as pm_total_btl_2,
    
    sum(case when date_flag = '{end_day_of_last_2month}' then net_sales else 0 end) as ppm_sales_2,
    sum(case when date_flag = '{end_day_of_last_2month}' then net_cost else 0 end) as ppm_cost_2,
    sum(case when date_flag = '{end_day_of_last_2month}' then total_unit else 0 end) as ppm_unit_2,
    sum(case when date_flag = '{end_day_of_last_2month}' then gm_amt else 0 end) as ppm_gm_2,
    sum(case when date_flag = '{end_day_of_last_2month}' then ngm_amt else 0 end) as ppm_ngm_2,
    sum(case when date_flag = '{end_day_of_last_2month}' then oplgm_amt else 0 end) as ppm_opl_2,
    sum(case when date_flag = '{end_day_of_last_2month}' then scm_usage else 0 end) as ppm_scm_usage_2,
    sum(case when date_flag = '{end_day_of_last_2month}' then tgm_amt else 0 end) as ppm_tgm_2,
    sum(case when date_flag = '{end_day_of_last_2month}' then scm_disc else 0 end) as ppm_scm_disc_2,
    sum(case when date_flag = '{end_day_of_last_2month}' then scm_ndisc else 0 end) as ppm_scm_ndisc_2,
    sum(case when date_flag = '{end_day_of_last_2month}' then ds_sales else 0 end) as ppm_ds_sales_2,
    sum(case when date_flag = '{end_day_of_last_2month}' then stock_sales else 0 end) as ppm_stock_sales_2,
    sum(case when date_flag = '{end_day_of_last_2month}' then ds_cost else 0 end) as ppm_ds_cost_2,
    sum(case when date_flag = '{end_day_of_last_2month}' then stock_cost else 0 end) as ppm_stock_cost_2,
    sum(case when date_flag = '{end_day_of_last_2month}' then ds_scm_usage else 0 end) as ppm_ds_scm_usage_2,
    sum(case when date_flag = '{end_day_of_last_2month}' then stock_scm_usage else 0 end) as ppm_stock_scm_usage_2,
    sum(case when date_flag = '{end_day_of_last_2month}' then cgp else 0 end) as ppm_cgp_2,
    sum(case when date_flag = '{end_day_of_last_2month}' then total_btl else 0 end) as ppm_total_btl_2
    from dw_{country}.dws_disty_brpt_vpl_mtd
    where date_flag in ('{end_day_of_last_2month}','{end_day_of_last_month}')
    group by
    pm_id,
    pm_mgr_id,
    pm_dir_id,
    pm_vp_id,
    seg_code,
    nvl(company_no,1) ),
    
    table_dt_month_last_year as (
    select
    pm_id,
    pm_mgr_id,
    pm_dir_id,
    pm_vp_id,
    seg_code,
    nvl(company_no,1) as company_no,
    sum(net_sales) as lm_sales_2,
    sum(net_cost) as lm_cost_2,
    sum(total_unit) as lm_unit_2,
    sum(gm_amt) as lm_gm_2,
    sum(ngm_amt) as lm_ngm_2,
    sum(oplgm_amt) as lm_opl_2,
    sum(scm_usage) as lm_scm_usage_2,
    sum(tgm_amt) as lm_tgm_2,
    sum(scm_disc) as lm_scm_disc_2,
    sum(scm_ndisc) as lm_scm_ndisc_2,
    sum(ds_sales) as lm_ds_sales_2,
    sum(stock_sales) as lm_stock_sales_2,
    sum(ds_cost) as lm_ds_cost_2,
    sum(stock_cost) as lm_stock_cost_2,
    sum(ds_scm_usage) as lm_ds_scm_usage_2,
    sum(stock_scm_usage) as lm_stock_scm_usage_2,
    sum(cgp) as lm_cgp_2,
    sum(total_btl) as lm_total_btl_2
    from dw_{country}.dws_disty_brpt_vpl_mtd
    where date_flag = '{end_day_of_same_month_of_last_year}'
    group by
    pm_id,
    pm_mgr_id,
    pm_dir_id,
    pm_vp_id,
    seg_code,
    nvl(company_no,1) )
    
    insert overwrite dm_{country}.dm_disty_brpt_pm_comb_mtd partition(date_flag = '{date_flag}')
    select
        table_dm.month_no,
        nvl(table_dm.pm_id,-3),
        table_dm.pm_name,
        nvl(table_dm.pm_mgr_id,-3),
        table_dm.pm_manager_name,
        nvl(table_dm.pm_dir_id,-3),
        table_dm.pm_director_name,
        nvl(table_dm.pm_vp_id,-3),
        table_dm.pm_vp_name,
        table_dm.seg_code,
        table_dm.company_no,
        nvl(table_dm.goal_nsales,0),
        nvl(table_dm.goal_gm,0),
        nvl(table_dm.goal_ngm,0),
        nvl(table_dm.goal_opl_gm,0),
        nvl(table_dm.goal_tgm,0),
        nvl(table_dm.goal_dos,0),
        nvl(table_dm.goal_pdt,0),
        nvl(table_dm.goal_total_btl,0),
        nvl(table_dm.d_sales,0),
        nvl(table_dm.d_cost,0),
        nvl(table_dm.d_unit,0),
        nvl(table_dm.d_gm,0),
        nvl(table_dm.d_ngm,0),
        nvl(table_dm.d_opl,0),
        nvl(table_dm.d_scm_usage,0),
        nvl(table_dm.d_tgm,0),
        nvl(table_dm.d_cgp,0),
        nvl(table_dm.d_total_btl,0),
        nvl(table_dm.w_sales,0),
        nvl(table_dm.w_cost,0),
        nvl(table_dm.w_unit,0),
        nvl(table_dm.w_gm,0),
        nvl(table_dm.w_ngm,0),
        nvl(table_dm.w_opl,0),
        nvl(table_dm.w_scm_usage,0),
        nvl(table_dm.w_tgm,0),
        nvl(table_dm.w_cgp,0),
        nvl(table_dm.w_total_btl,0),
        nvl(table_dm.m_sales,0),
        nvl(table_dm.m_cost,0),
        nvl(table_dm.m_unit,0),
        nvl(table_dm.m_gm,0),
        nvl(table_dm.m_ngm,0),
        nvl(table_dm.m_opl,0),
        nvl(table_dm.m_scm_usage,0),
        nvl(table_dm.m_tgm,0),
        nvl(table_dm.m_scm_disc,0),
        nvl(table_dm.m_scm_ndisc,0),
        nvl(table_dm.m_ds_sales,0),
        nvl(table_dm.m_stock_sales,0),
        nvl(table_dm.m_ds_cost,0),
        nvl(table_dm.m_stock_cost,0),
        nvl(table_dm.m_ds_scm_usage,0),
        nvl(table_dm.m_stock_scm_usage,0),
        nvl(table_dm.m_cgp,0),
        nvl(table_dm.m_total_btl,0),
        nvl(table_dm.pm_sales,0),
        nvl(table_dm.pm_cost,0),
        nvl(table_dm.pm_unit,0),
        nvl(table_dm.pm_gm,0),
        nvl(table_dm.pm_ngm,0),
        nvl(table_dm.pm_opl,0),
        nvl(table_dm.pm_scm_usage,0),
        nvl(table_dm.pm_tgm,0),
        nvl(table_dm.pm_scm_disc,0),
        nvl(table_dm.pm_scm_ndisc,0),
        nvl(table_dm.pm_ds_sales,0),
        nvl(table_dm.pm_stock_sales,0),
        nvl(table_dm.pm_ds_cost,0),
        nvl(table_dm.pm_stock_cost,0),
        nvl(table_dm.pm_ds_scm_usage,0),
        nvl(table_dm.pm_stock_scm_usage,0),
        nvl(table_dm.pm_cgp,0),
        nvl(table_dm.pm_total_btl,0),
        nvl(table_dm.ppm_sales,0),
        nvl(table_dm.ppm_cost,0),
        nvl(table_dm.ppm_unit,0),
        nvl(table_dm.ppm_gm,0),
        nvl(table_dm.ppm_ngm,0),
        nvl(table_dm.ppm_opl,0),
        nvl(table_dm.ppm_scm_usage,0),
        nvl(table_dm.ppm_tgm,0),
        nvl(table_dm.ppm_scm_disc,0),
        nvl(table_dm.ppm_scm_ndisc,0),
        nvl(table_dm.ppm_ds_sales,0),
        nvl(table_dm.ppm_stock_sales,0),
        nvl(table_dm.ppm_ds_cost,0),
        nvl(table_dm.ppm_stock_cost,0),
        nvl(table_dm.ppm_ds_scm_usage,0),
        nvl(table_dm.ppm_stock_scm_usage,0),
        nvl(table_dm.ppm_cgp,0),
        nvl(table_dm.ppm_total_btl,0),
        nvl(table_dm.lm_sales,0),
        nvl(table_dm.lm_cost,0),
        nvl(table_dm.lm_unit,0),
        nvl(table_dm.lm_gm,0),
        nvl(table_dm.lm_ngm,0),
        nvl(table_dm.lm_opl,0),
        nvl(table_dm.lm_scm_usage,0),
        nvl(table_dm.lm_tgm,0),
        nvl(table_dm.lm_scm_disc,0),
        nvl(table_dm.lm_scm_ndisc,0),
        nvl(table_dm.lm_ds_sales,0),
        nvl(table_dm.lm_stock_sales,0),
        nvl(table_dm.lm_ds_cost,0),
        nvl(table_dm.lm_stock_cost,0),
        nvl(table_dm.lm_ds_scm_usage,0),
        nvl(table_dm.lm_stock_scm_usage,0),
        nvl(table_dm.lm_cgp,0),
        nvl(table_dm.lm_total_btl,0),
        nvl(table_dm.bo_gross_sales,0),
        nvl(table_dm.bo_gross_cost,0),
        nvl(table_dm.bo_total_unit,0),
        nvl(table_dm.bo_gm_amt,0),
        nvl(table_dm.so_gross_sales,0),
        nvl(table_dm.so_gross_cost,0),
        nvl(table_dm.so_total_unit,0),
        nvl(table_dm.so_gm_amt,0),
        nvl(table_dm.bo_age0_7,0),
        nvl(table_dm.bo_age8_14,0),
        nvl(table_dm.bo_age15_21,0),
        nvl(table_dm.bo_age21_up,0),
        nvl(table_dm.so_age0_7,0),
        nvl(table_dm.so_age8_14,0),
        nvl(table_dm.so_age15_21,0),
        nvl(table_dm.so_age21_up,0),
        nvl(table_dm.reg_inv,0),
        nvl(table_dm.reg_inv_age0_30,0),
        nvl(table_dm.reg_inv_age31_60,0),
        nvl(table_dm.reg_inv_age61_90,0),
        nvl(table_dm.reg_inv_age90_up,0),
        nvl(table_dm.rma_inv,0),
        nvl(table_dm.rma_inv_age0_30,0),
        nvl(table_dm.rma_inv_age31_60,0),
        nvl(table_dm.rma_inv_age61_90,0),
        nvl(table_dm.rma_inv_age90_up,0),
        nvl(table_dm.oh_cost,0),
        nvl(table_dm.oo_cost,0),
        nvl(table_dm.oh_qty,0),
        nvl(table_dm.oo_qty,0),
        nvl(table_dm.rr_unit,0),
        nvl(table_dm.rr_sales,0),
        nvl(table_dm.rr_cost,0),
        nvl(table_dm.rr_gm,0),
        nvl(table_dm.rr_ngm,0),
        nvl(table_dm.rr_opl,0),
        nvl(table_dm.rr_cgp,0),
        nvl(table_dm.rr_total_btl,0),
        nvl(table_dm.rr_tgm,0),
        table_dm.etl_timestamp,
    
        nvl(table_last_dt_month.pm_sales_2,0),
        nvl(table_last_dt_month.pm_cost_2,0),
        nvl(table_last_dt_month.pm_unit_2,0),
        nvl(table_last_dt_month.pm_gm_2,0),
        nvl(table_last_dt_month.pm_ngm_2,0),
        nvl(table_last_dt_month.pm_opl_2,0),
        nvl(table_last_dt_month.pm_scm_usage_2,0),
        nvl(table_last_dt_month.pm_tgm_2,0),
        nvl(table_last_dt_month.pm_scm_disc_2,0),
        nvl(table_last_dt_month.pm_scm_ndisc_2,0),
        nvl(table_last_dt_month.pm_ds_sales_2,0),
        nvl(table_last_dt_month.pm_stock_sales_2,0),
        nvl(table_last_dt_month.pm_ds_cost_2,0),
        nvl(table_last_dt_month.pm_stock_cost_2,0),
        nvl(table_last_dt_month.pm_ds_scm_usage_2,0),
        nvl(table_last_dt_month.pm_stock_scm_usage_2,0),
        nvl(table_last_dt_month.pm_cgp_2,0),
        nvl(table_last_dt_month.pm_total_btl_2,0),
        nvl(table_last_dt_month.ppm_sales_2,0),
        nvl(table_last_dt_month.ppm_cost_2,0),
        nvl(table_last_dt_month.ppm_unit_2,0),
        nvl(table_last_dt_month.ppm_gm_2,0),
        nvl(table_last_dt_month.ppm_ngm_2,0),
        nvl(table_last_dt_month.ppm_opl_2,0),
        nvl(table_last_dt_month.ppm_scm_usage_2,0),
        nvl(table_last_dt_month.ppm_tgm_2,0),
        nvl(table_last_dt_month.ppm_scm_disc_2,0),
        nvl(table_last_dt_month.ppm_scm_ndisc_2,0),
        nvl(table_last_dt_month.ppm_ds_sales_2,0),
        nvl(table_last_dt_month.ppm_stock_sales_2,0),
        nvl(table_last_dt_month.ppm_ds_cost_2,0),
        nvl(table_last_dt_month.ppm_stock_cost_2,0),
        nvl(table_last_dt_month.ppm_ds_scm_usage_2,0),
        nvl(table_last_dt_month.ppm_stock_scm_usage_2,0),
        nvl(table_last_dt_month.ppm_cgp_2,0),
        nvl(table_last_dt_month.ppm_total_btl_2,0),
        nvl(table_dt_month_last_year.lm_sales_2,0),
        nvl(table_dt_month_last_year.lm_cost_2,0),
        nvl(table_dt_month_last_year.lm_unit_2,0),
        nvl(table_dt_month_last_year.lm_gm_2,0),
        nvl(table_dt_month_last_year.lm_ngm_2,0),
        nvl(table_dt_month_last_year.lm_opl_2,0),
        nvl(table_dt_month_last_year.lm_scm_usage_2,0),
        nvl(table_dt_month_last_year.lm_tgm_2,0),
        nvl(table_dt_month_last_year.lm_scm_disc_2,0),
        nvl(table_dt_month_last_year.lm_scm_ndisc_2,0),
        nvl(table_dt_month_last_year.lm_ds_sales_2,0),
        nvl(table_dt_month_last_year.lm_stock_sales_2,0),
        nvl(table_dt_month_last_year.lm_ds_cost_2,0),
        nvl(table_dt_month_last_year.lm_stock_cost_2,0),
        nvl(table_dt_month_last_year.lm_ds_scm_usage_2,0),
        nvl(table_dt_month_last_year.lm_stock_scm_usage_2,0),
        nvl(table_dt_month_last_year.lm_cgp_2,0),
        nvl(table_dt_month_last_year.lm_total_btl_2,0),
        nvl(table_dm.m_p91_cost,0),
        nvl(table_dm.d_fx_cost,0),
        nvl(table_dm.w_fx_cost,0),
        nvl(table_dm.m_fx_cost,0),
        nvl(table_dm.pm_fx_cost,0),
        nvl(table_dm.ppm_fx_cost,0),
        nvl(table_dm.lm_fx_cost,0),
        nvl(table_dm.d_oplgm_plus_amt   ,0),
        nvl(table_dm.w_oplgm_plus_amt   ,0),
        nvl(table_dm.m_oplgm_plus_amt   ,0),
        nvl(table_dm.pm_oplgm_plus_amt  ,0),
        nvl(table_dm.ppm_oplgm_plus_amt ,0),
        nvl(table_dm.lm_oplgm_plus_amt  ,0),
        nvl(table_dm.rr_oplgm_plus_amt  ,0),
        nvl(table_dm.goal_oplgm_plus_amt,0)
    from (select *
          from dm_{country}.dm_disty_brpt_pm_comb_mtd
          where date_flag = '{date_flag}') as table_dm
    left join table_last_dt_month
    on table_dm.pm_id = table_last_dt_month.pm_id
    and table_dm.pm_mgr_id = table_last_dt_month.pm_mgr_id
    and table_dm.pm_dir_id = table_last_dt_month.pm_dir_id
    and table_dm.pm_vp_id = table_last_dt_month.pm_vp_id
    and table_dm.seg_code = table_last_dt_month.seg_code
    and table_dm.company_no = table_last_dt_month.company_no
    
    left join table_dt_month_last_year
    on table_dm.pm_id = table_dt_month_last_year.pm_id
    and table_dm.pm_mgr_id = table_dt_month_last_year.pm_mgr_id
    and table_dm.pm_dir_id = table_dt_month_last_year.pm_dir_id
    and table_dm.pm_vp_id = table_dt_month_last_year.pm_vp_id
    and table_dm.seg_code = table_dt_month_last_year.seg_code
    and table_dm.company_no = table_dt_month_last_year.company_no
    """.format(country=country, date_flag=date_flag, dt_month=dt_month,
               end_day_of_last_month=end_day_of_last_month,
               end_day_of_last_2month=end_day_of_last_2month,
               end_day_of_same_month_of_last_year=end_day_of_same_month_of_last_year)
    run_sql(sql)

main()