# -*- coding: utf-8 -*-
# @Time : 9/25/2023 10:17 AM
# @Author : Marvin Ma

from synnex.bigdata import conf
from synnex.bigdata.pyspark import run_sql

# dw_{country}.dws_disty_brpt_vpl_comb_mtd


def main():
    country = conf.get("country")
    date_flag = conf.get("date_flag")  # date_flag = yesterday = @process_date
    dt_month = conf.get("dt_month")  # date_flag format to 'yyyy-MM'
    etl_timestamp = conf.get("etl_timestamp")

    run_sql("""
    with
    table_goal as (
    select
        vend_no,
        seg_code,
        pm,
        manager,
        director,
        vp,
        company_no,
        sum(net_sales_local_currency)               as goal_nsales,
        sum(gm * net_sales_local_currency / 100)    as goal_gm,
        sum(ngm * net_sales_local_currency / 100)   as goal_ngm,
        null                                        as goal_opl_gm,
        null                                        as goal_oplgm_plus_amt,
        sum(tgm * net_sales_local_currency / 100)   as goal_tgm,
        sum(  nvl(dos_local_currency,0) )           as goal_dos,
        sum(pdt * net_sales_local_currency / 100)   as goal_pdt,
        sum(btl * net_sales_local_currency / 100)   as goal_total_btl
    from dw_${country}.dwd_disty_pm_report_goal_view --unique id : period + seg_code + vp + director + manager + pm + vend_no + vpl_no
    where period = ${month_no}
    and vend_no <> 0
    and vpl_no = 0
    group by 
        vend_no,
        seg_code,
        pm,
        manager,
        director,
        vp,
        company_no
    having goal_nsales <> 0),
    
    table_dwd as (
    select 
        vend_no,
        master_vend_no,
        seg_code,
        nvl(company_no,1) as company_no,
        pm_id,
        pm_mgr_id,
        pm_dir_id,
        pm_vp_id,
    
        sum(d_sales) as d_sales,
        sum(d_cost) as d_cost,
        sum(d_unit) as d_unit,
        sum(d_gm) as d_gm,
        sum(d_ngm) as d_ngm,
        sum(d_opl) as d_opl,
        sum(d_oplgm_plus_amt) as d_oplgm_plus_amt,
        sum(d_scm_usage) as d_scm_usage,
        sum(d_tgm) as d_tgm,
        sum(d_cgp) as d_cgp,
        sum(d_total_btl) as d_total_btl,
        sum(w_sales) as w_sales,
        sum(w_cost) as w_cost,
        sum(w_unit) as w_unit,
        sum(w_gm) as w_gm,
        sum(w_ngm) as w_ngm,
        sum(w_opl) as w_opl,
        sum(w_oplgm_plus_amt) as w_oplgm_plus_amt,
        sum(w_scm_usage) as w_scm_usage,
        sum(w_tgm) as w_tgm,
        sum(w_cgp) as w_cgp,
        sum(w_total_btl) as w_total_btl,
        sum(m_sales) as m_sales,
        sum(m_cost) as m_cost,
        sum(m_unit) as m_unit,
        sum(m_gm) as m_gm,
        sum(m_ngm) as m_ngm,
        sum(m_opl) as m_opl,
        sum(m_oplgm_plus_amt) as m_oplgm_plus_amt,
        sum(m_scm_usage) as m_scm_usage,
        sum(m_tgm) as m_tgm,
        sum(m_scm_disc) as m_scm_disc,
        sum(m_scm_ndisc) as m_scm_ndisc,
        sum(m_ds_sales) as m_ds_sales,
        sum(m_stock_sales) as m_stock_sales,
        sum(m_ds_cost) as m_ds_cost,
        sum(m_stock_cost) as m_stock_cost,
        sum(m_ds_scm_usage) as m_ds_scm_usage,
        sum(m_stock_scm_usage) as m_stock_scm_usage,
        sum(m_cgp) as m_cgp,
        sum(m_total_btl) as m_total_btl,
        sum(pm_sales) as pm_sales,
        sum(pm_cost) as pm_cost,
        sum(pm_unit) as pm_unit,
        sum(pm_gm) as pm_gm,
        sum(pm_ngm) as pm_ngm,
        sum(pm_opl) as pm_opl,
        sum(pm_oplgm_plus_amt) as pm_oplgm_plus_amt,
        sum(pm_scm_usage) as pm_scm_usage,
        sum(pm_tgm) as pm_tgm,
        sum(pm_scm_disc) as pm_scm_disc,
        sum(pm_scm_ndisc) as pm_scm_ndisc,
        sum(pm_ds_sales) as pm_ds_sales,
        sum(pm_stock_sales) as pm_stock_sales,
        sum(pm_ds_cost) as pm_ds_cost,
        sum(pm_stock_cost) as pm_stock_cost,
        sum(pm_ds_scm_usage) as pm_ds_scm_usage,
        sum(pm_stock_scm_usage) as pm_stock_scm_usage,
        sum(pm_cgp) as pm_cgp,
        sum(pm_total_btl) as pm_total_btl,
        sum(ppm_sales) as ppm_sales,
        sum(ppm_cost) as ppm_cost,
        sum(ppm_unit) as ppm_unit,
        sum(ppm_gm) as ppm_gm,
        sum(ppm_ngm) as ppm_ngm,
        sum(ppm_opl) as ppm_opl,
        sum(ppm_oplgm_plus_amt) as ppm_oplgm_plus_amt,
        sum(ppm_scm_usage) as ppm_scm_usage,
        sum(ppm_tgm) as ppm_tgm,
        sum(ppm_scm_disc) as ppm_scm_disc,
        sum(ppm_scm_ndisc) as ppm_scm_ndisc,
        sum(ppm_ds_sales) as ppm_ds_sales,
        sum(ppm_stock_sales) as ppm_stock_sales,
        sum(ppm_ds_cost) as ppm_ds_cost,
        sum(ppm_stock_cost) as ppm_stock_cost,
        sum(ppm_ds_scm_usage) as ppm_ds_scm_usage,
        sum(ppm_stock_scm_usage) as ppm_stock_scm_usage,
        sum(ppm_cgp) as ppm_cgp,
        sum(ppm_total_btl) as ppm_total_btl,
        sum(lm_sales) as lm_sales,
        sum(lm_cost) as lm_cost,
        sum(lm_unit) as lm_unit,
        sum(lm_gm) as lm_gm,
        sum(lm_ngm) as lm_ngm,
        sum(lm_opl) as lm_opl,
        sum(lm_oplgm_plus_amt) as lm_oplgm_plus_amt,
        sum(lm_scm_usage) as lm_scm_usage,
        sum(lm_tgm) as lm_tgm,
        sum(lm_scm_disc) as lm_scm_disc,
        sum(lm_scm_ndisc) as lm_scm_ndisc,
        sum(lm_ds_sales) as lm_ds_sales,
        sum(lm_stock_sales) as lm_stock_sales,
        sum(lm_ds_cost) as lm_ds_cost,
        sum(lm_stock_cost) as lm_stock_cost,
        sum(lm_ds_scm_usage) as lm_ds_scm_usage,
        sum(lm_stock_scm_usage) as lm_stock_scm_usage,
        sum(lm_cgp) as lm_cgp,
        sum(lm_total_btl) as lm_total_btl,
        sum(bo_gross_sales) as bo_gross_sales,
        sum(bo_gross_cost) as bo_gross_cost,
        sum(bo_total_unit) as bo_total_unit,
        sum(bo_gm_amt) as bo_gm_amt,
        sum(so_gross_sales) as so_gross_sales,
        sum(so_gross_cost) as so_gross_cost,
        sum(so_total_unit) as so_total_unit,
        sum(so_gm_amt) as so_gm_amt,
        sum(bo_age0_7) as bo_age0_7,
        sum(bo_age8_14) as bo_age8_14,
        sum(bo_age15_21) as bo_age15_21,
        sum(bo_age21_up) as bo_age21_up,
        sum(so_age0_7) as so_age0_7,
        sum(so_age8_14) as so_age8_14,
        sum(so_age15_21) as so_age15_21,
        sum(so_age21_up) as so_age21_up,
        sum(reg_inv) as reg_inv,
        sum(reg_inv_age0_30) as reg_inv_age0_30,
        sum(reg_inv_age31_60) as reg_inv_age31_60,
        sum(reg_inv_age61_90) as reg_inv_age61_90,
        sum(reg_inv_age90_up) as reg_inv_age90_up,
        sum(rma_inv) as rma_inv,
        sum(rma_inv_age0_30) as rma_inv_age0_30,
        sum(rma_inv_age31_60) as rma_inv_age31_60,
        sum(rma_inv_age61_90) as rma_inv_age61_90,
        sum(rma_inv_age90_up) as rma_inv_age90_up,
        sum(oh_cost) as oh_cost,
        sum(oo_cost) as oo_cost,
        sum(oh_qty) as oh_qty,
        sum(oo_qty) as oo_qty,
        sum(rr_unit) as rr_unit,
        sum(rr_sales) as rr_sales,
        sum(rr_cost) as rr_cost,
        sum(rr_gm) as rr_gm,
        sum(rr_ngm) as rr_ngm,
        sum(rr_opl) as rr_opl,
        sum(rr_oplgm_plus_amt) as rr_oplgm_plus_amt,
        sum(rr_cgp) as rr_cgp,
        sum(rr_total_btl) as rr_total_btl,
        sum(rr_tgm) as rr_tgm,
        sum(m_p91_cost) as m_p91_cost,
        sum(d_fx_cost) as d_fx_cost,
        sum(w_fx_cost) as w_fx_cost,
        sum(m_fx_cost) as m_fx_cost,
        sum(pm_fx_cost) as pm_fx_cost,
        sum(ppm_fx_cost) as ppm_fx_cost,
        sum(lm_fx_cost) as lm_fx_cost
    from dw_${country}.dws_disty_brpt_vpl_comb_mtd
    where date_flag = '${date_flag}'  
    group by
        vend_no,
        master_vend_no,
        seg_code,
        nvl(company_no,1),
        pm_id,
        pm_mgr_id,
        pm_dir_id,
        pm_vp_id)

    insert overwrite table dw_${country}.dws_disty_brpt_vend_comb_mtd partition(date_flag = '${date_flag}')
    select
        ${month_no},

        coalesce(table_dwd.vend_no,table_goal.vend_no,-3),
        table_vend.vend_name,
        coalesce(table_dwd.master_vend_no,table_vend.master_vend_no,-3),
        table_mvend.cis_mk_name as master_vend_name,
        nvl(table_dwd.seg_code,table_goal.seg_code),
        coalesce(table_dwd.company_no,table_goal.company_no) as company_no,

        nvl(table_goal.goal_nsales,0),
        nvl(table_goal.goal_gm,0),
        nvl(table_goal.goal_ngm,0),
        nvl(table_goal.goal_opl_gm,0),
        nvl(table_goal.goal_tgm,0),
        nvl(table_goal.goal_dos,0),
        nvl(table_goal.goal_pdt,0),
        nvl(table_goal.goal_total_btl,0),

        nvl(table_dwd.d_sales,0),
        nvl(table_dwd.d_cost,0),
        nvl(table_dwd.d_unit,0),
        nvl(table_dwd.d_gm,0),
        nvl(table_dwd.d_ngm,0),
        nvl(table_dwd.d_opl,0),
        nvl(table_dwd.d_scm_usage,0),
        nvl(table_dwd.d_tgm,0),
        nvl(table_dwd.d_cgp,0),
        nvl(table_dwd.d_total_btl,0),
        nvl(table_dwd.w_sales,0),
        nvl(table_dwd.w_cost,0),
        nvl(table_dwd.w_unit,0),
        nvl(table_dwd.w_gm,0),
        nvl(table_dwd.w_ngm,0),
        nvl(table_dwd.w_opl,0),
        nvl(table_dwd.w_scm_usage,0),
        nvl(table_dwd.w_tgm,0),
        nvl(table_dwd.w_cgp,0),
        nvl(table_dwd.w_total_btl,0),
        nvl(table_dwd.m_sales,0),
        nvl(table_dwd.m_cost,0),
        nvl(table_dwd.m_unit,0),
        nvl(table_dwd.m_gm,0),
        nvl(table_dwd.m_ngm,0),
        nvl(table_dwd.m_opl,0),
        nvl(table_dwd.m_scm_usage,0),
        nvl(table_dwd.m_tgm,0),
        nvl(table_dwd.m_scm_disc,0),
        nvl(table_dwd.m_scm_ndisc,0),
        nvl(table_dwd.m_ds_sales,0),
        nvl(table_dwd.m_stock_sales,0),
        nvl(table_dwd.m_ds_cost,0),
        nvl(table_dwd.m_stock_cost,0),
        nvl(table_dwd.m_ds_scm_usage,0),
        nvl(table_dwd.m_stock_scm_usage,0),
        nvl(table_dwd.m_cgp,0),
        nvl(table_dwd.m_total_btl,0),
        nvl(table_dwd.pm_sales,0),
        nvl(table_dwd.pm_cost,0),
        nvl(table_dwd.pm_unit,0),
        nvl(table_dwd.pm_gm,0),
        nvl(table_dwd.pm_ngm,0),
        nvl(table_dwd.pm_opl,0),
        nvl(table_dwd.pm_scm_usage,0),
        nvl(table_dwd.pm_tgm,0),
        nvl(table_dwd.pm_scm_disc,0),
        nvl(table_dwd.pm_scm_ndisc,0),
        nvl(table_dwd.pm_ds_sales,0),
        nvl(table_dwd.pm_stock_sales,0),
        nvl(table_dwd.pm_ds_cost,0),
        nvl(table_dwd.pm_stock_cost,0),
        nvl(table_dwd.pm_ds_scm_usage,0),
        nvl(table_dwd.pm_stock_scm_usage,0),
        nvl(table_dwd.pm_cgp,0),
        nvl(table_dwd.pm_total_btl,0),
        nvl(table_dwd.ppm_sales,0),
        nvl(table_dwd.ppm_cost,0),
        nvl(table_dwd.ppm_unit,0),
        nvl(table_dwd.ppm_gm,0),
        nvl(table_dwd.ppm_ngm,0),
        nvl(table_dwd.ppm_opl,0),
        nvl(table_dwd.ppm_scm_usage,0),
        nvl(table_dwd.ppm_tgm,0),
        nvl(table_dwd.ppm_scm_disc,0),
        nvl(table_dwd.ppm_scm_ndisc,0),
        nvl(table_dwd.ppm_ds_sales,0),
        nvl(table_dwd.ppm_stock_sales,0),
        nvl(table_dwd.ppm_ds_cost,0),
        nvl(table_dwd.ppm_stock_cost,0),
        nvl(table_dwd.ppm_ds_scm_usage,0),
        nvl(table_dwd.ppm_stock_scm_usage,0),
        nvl(table_dwd.ppm_cgp,0),
        nvl(table_dwd.ppm_total_btl,0),
        nvl(table_dwd.lm_sales,0),
        nvl(table_dwd.lm_cost,0),
        nvl(table_dwd.lm_unit,0),
        nvl(table_dwd.lm_gm,0),
        nvl(table_dwd.lm_ngm,0),
        nvl(table_dwd.lm_opl,0),
        nvl(table_dwd.lm_scm_usage,0),
        nvl(table_dwd.lm_tgm,0),
        nvl(table_dwd.lm_scm_disc,0),
        nvl(table_dwd.lm_scm_ndisc,0),
        nvl(table_dwd.lm_ds_sales,0),
        nvl(table_dwd.lm_stock_sales,0),
        nvl(table_dwd.lm_ds_cost,0),
        nvl(table_dwd.lm_stock_cost,0),
        nvl(table_dwd.lm_ds_scm_usage,0),
        nvl(table_dwd.lm_stock_scm_usage,0),
        nvl(table_dwd.lm_cgp,0),
        nvl(table_dwd.lm_total_btl,0),
        nvl(table_dwd.bo_gross_sales,0),
        nvl(table_dwd.bo_gross_cost,0),
        nvl(table_dwd.bo_total_unit,0),
        nvl(table_dwd.bo_gm_amt,0),
        nvl(table_dwd.so_gross_sales,0),
        nvl(table_dwd.so_gross_cost,0),
        nvl(table_dwd.so_total_unit,0),
        nvl(table_dwd.so_gm_amt,0),
        nvl(table_dwd.bo_age0_7,0),
        nvl(table_dwd.bo_age8_14,0),
        nvl(table_dwd.bo_age15_21,0),
        nvl(table_dwd.bo_age21_up,0),
        nvl(table_dwd.so_age0_7,0),
        nvl(table_dwd.so_age8_14,0),
        nvl(table_dwd.so_age15_21,0),
        nvl(table_dwd.so_age21_up,0),
        nvl(table_dwd.reg_inv,0),
        nvl(table_dwd.reg_inv_age0_30,0),
        nvl(table_dwd.reg_inv_age31_60,0),
        nvl(table_dwd.reg_inv_age61_90,0),
        nvl(table_dwd.reg_inv_age90_up,0),
        nvl(table_dwd.rma_inv,0),
        nvl(table_dwd.rma_inv_age0_30,0),
        nvl(table_dwd.rma_inv_age31_60,0),
        nvl(table_dwd.rma_inv_age61_90,0),
        nvl(table_dwd.rma_inv_age90_up,0),
        nvl(table_dwd.oh_cost,0),
        nvl(table_dwd.oo_cost,0),
        nvl(table_dwd.oh_qty,0),
        nvl(table_dwd.oo_qty,0),
        nvl(table_dwd.rr_unit,0),
        nvl(table_dwd.rr_sales,0),
        nvl(table_dwd.rr_cost,0),
        nvl(table_dwd.rr_gm,0),
        nvl(table_dwd.rr_ngm,0),
        nvl(table_dwd.rr_opl,0),
        nvl(table_dwd.rr_cgp,0),
        nvl(table_dwd.rr_total_btl,0),
        nvl(table_dwd.rr_tgm,0),
        '${etl_timestamp}',
        nvl(table_dwd.m_p91_cost,0),
        coalesce(table_dwd.pm_id,table_goal.pm,-3),
        coalesce(table_dwd.pm_mgr_id,table_goal.manager,-3),
        coalesce(table_dwd.pm_dir_id,table_goal.director,-3),
        coalesce(table_dwd.pm_vp_id,table_goal.vp,-3),
        nvl(table_dwd.d_fx_cost,0),
        nvl(table_dwd.w_fx_cost,0),
        nvl(table_dwd.m_fx_cost,0),
        nvl(table_dwd.pm_fx_cost,0),
        nvl(table_dwd.ppm_fx_cost,0),
        nvl(table_dwd.lm_fx_cost,0),
        nvl(table_dwd.d_oplgm_plus_amt   ,0),
        nvl(table_dwd.w_oplgm_plus_amt   ,0),
        nvl(table_dwd.m_oplgm_plus_amt   ,0),
        nvl(table_dwd.pm_oplgm_plus_amt  ,0),
        nvl(table_dwd.ppm_oplgm_plus_amt ,0),
        nvl(table_dwd.lm_oplgm_plus_amt  ,0),
        nvl(table_dwd.rr_oplgm_plus_amt  ,0),
        nvl(table_goal.goal_oplgm_plus_amt,0)
    from table_dwd
    full join table_goal
    on table_dwd.vend_no = table_goal.vend_no
    and table_dwd.seg_code = table_goal.seg_code
    and table_dwd.pm_id = table_goal.pm
    and table_dwd.pm_mgr_id = table_goal.manager
    and table_dwd.pm_dir_id = table_goal.director
    and table_dwd.pm_vp_id = table_goal.vp
    and (table_dwd.company_no = table_goal.company_no or table_goal.company_no = -1)
    
    left join (select *
               from dim_${country}.dim_pub_vendor_info_df
               where date_flag = '${date_flag}') as table_vend
    on nvl(table_dwd.vend_no,table_goal.vend_no) = table_vend.vend_no
    
    left join (select *
               from dim_${country}.dim_pub_vendor_info_df
               where date_flag = '${date_flag}') as table_mvend
    on nvl(table_dwd.master_vend_no,table_vend.master_vend_no) = table_mvend.vend_no
    """)


main()