# -*- coding: utf-8 -*-
# @Time : 12/14/2023 10:27 AM
# @Author : Marvin Ma

from synnex.bigdata import conf
from synnex.bigdata.pyspark import run_sql


def main():

    run_sql("""
    insert overwrite table dw_${country}.dws_disty_brpt_bd_vpl_wtd partition(dt_week)
    select
        table_dim.w as week_no,
        table_dim.max_date_flag as date_flag,

        project_no,
        project_name,
        task_no,
        task_name,
        company_no,
        vpl_no,
        vpl_code,
        vpc_group_id,
        vpc_group_desc,
        vend_no,
        vend_name,
        master_vend_no,
        master_vend_name,
        seg_code,
    
        sum(gross_sales),
        sum(net_sales),
        sum(gross_cost),
        sum(net_cost),
        sum(scm_usage),
        sum(ds_sales),
        sum(stock_sales),
        sum(ds_cost),
        sum(stock_cost),
        sum(ds_scm_usage),
        sum(stock_scm_usage),
        sum(total_unit),
        sum(total_weight),
    
        sum(cgp),
        sum(total_btl),
        sum(tgm_amt),
        sum(gm_amt),
        sum(ngm_amt),
        sum(oplgm_amt),
    
        SUM(case when table_left.date_flag = table_dim.max_date_flag then bo_gross_sales else 0 end) as bo_gross_sales,
        SUM(case when table_left.date_flag = table_dim.max_date_flag then bo_gross_cost  else 0 end) as bo_gross_cost,
        SUM(case when table_left.date_flag = table_dim.max_date_flag then bo_total_unit  else 0 end) as bo_total_unit,
        SUM(case when table_left.date_flag = table_dim.max_date_flag then bo_gm_amt      else 0 end) as bo_gm_amt,
        SUM(case when table_left.date_flag = table_dim.max_date_flag then so_gross_sales else 0 end) as so_gross_sales,
        SUM(case when table_left.date_flag = table_dim.max_date_flag then so_gross_cost  else 0 end) as so_gross_cost,
        SUM(case when table_left.date_flag = table_dim.max_date_flag then so_total_unit  else 0 end) as so_total_unit,
        SUM(case when table_left.date_flag = table_dim.max_date_flag then so_gm_amt      else 0 end) as so_gm_amt,
        SUM(case when table_left.date_flag = table_dim.max_date_flag then bo_age0_7      else 0 end) as bo_age0_7,
        SUM(case when table_left.date_flag = table_dim.max_date_flag then bo_age8_14     else 0 end) as bo_age8_14,
        SUM(case when table_left.date_flag = table_dim.max_date_flag then bo_age15_21    else 0 end) as bo_age15_21,
        SUM(case when table_left.date_flag = table_dim.max_date_flag then bo_age21_up    else 0 end) as bo_age21_up,
        SUM(case when table_left.date_flag = table_dim.max_date_flag then so_age0_7      else 0 end) as so_age0_7,
        SUM(case when table_left.date_flag = table_dim.max_date_flag then so_age8_14     else 0 end) as so_age8_14,
        SUM(case when table_left.date_flag = table_dim.max_date_flag then so_age15_21    else 0 end) as so_age15_21,
        SUM(case when table_left.date_flag = table_dim.max_date_flag then so_age21_up    else 0 end) as so_age21_up,
    
        sum(ap_finance),
        sum(inv_cost),
        sum(inv_reserve),
        sum(cr_risk_cterm),
        sum(flr_synnex),
        sum(direct_credit),
        sum(csgn_edi_fee),
        sum(corporate),
        sum(sfs),
        sum(scm_risk),
        sum(flr_vendor),
        sum(cust_finance_sales),
        sum(cust_pmt_disc),
        sum(cvr_rm),
        sum(ar_fin_recovery),
        sum(mfg_oh),
        sum(cust_finance),
        sum(rma),
        sum(hc_sales),
        sum(order_overhead),
        sum(margin_share),
        sum(ap_adj),
        sum(pdt),
        sum(scm_cost),
        sum(infrastructure),
        sum(marketing),
        sum(coop),
        sum(one_time_btl),
        sum(hbtl),
        sum(scm_profit_adj),
        sum(hc_pm),
        sum(hc_bd),
        sum(btl),
        sum(btl_sales),
        sum(btl_backout),
        sum(cust_rebate),
        sum(mof),
        sum(frt_out_load),
        sum(frt_out_exp),
        sum(whoh_pack),
        sum(frt_ob_recovery),
        sum(frt_ib_recovery),
        sum(others),
        sum(others_sales),
        sum(scm_disc),
        sum(scm_ndisc),
        sum(frt_in),
        sum(trans_btl),
        sum(trans_btl_sales),
        '${etl_timestamp}',
        b33_flag,
        sum(fx_cost),
        sum(btl_sales_for_opl) as  btl_sales_for_opl ,       
		sum(trans_btl_sales_for_opl) as trans_btl_sales_for_opl,   
		sum(pdt_for_opl) as pdt_for_opl,               
		sum(cust_rebate_for_opl) as cust_rebate_for_opl,       
		sum(cvr_rm_for_opl) as cvr_rm_for_opl,            
		sum(btl_backout_for_opl) as btl_backout_for_opl,       
		sum(cust_pmt_disc_for_opl) as cust_pmt_disc_for_opl,     
		sum(cust_finance_sales_for_opl) as cust_finance_sales_for_opl,
		sum(rma_for_opl) as rma_for_opl,               
		sum(ar_fin_recovery_for_opl) as ar_fin_recovery_for_opl,   
		sum(order_overhead_for_opl) as order_overhead_for_opl,    
		sum(frt_out_exp_for_opl) as frt_out_exp_for_opl,       
		sum(frt_ob_recovery_for_opl) as frt_ob_recovery_for_opl,  
		sum(oplgm_plus_amt) as oplgm_plus_amt,
        table_dim.week_flag
    from (select * from dw_${country}.dws_disty_brpt_bd_vpl_1d
          where date_flag between '${week_begin_of_firstday}' and '${date_flag}') as table_left
    left join (select 
               w,
               week_flag,
               date_flag,
               max(date_flag) over(partition by w,week_flag) as max_date_flag
               from dim_${country}.dim_pub_date
               where date_flag between '${week_begin_of_firstday}' and '${date_flag}') as table_dim
    on table_left.date_flag = table_dim.date_flag
    group by
        table_dim.w,
        table_dim.week_flag,
        table_dim.max_date_flag,
        project_no,
        project_name,
        task_no,
        task_name,
        b33_flag,
        company_no,
        vpl_no,
        vpl_code,
        vpc_group_id,
        vpc_group_desc,
        vend_no,
        vend_name,
        master_vend_no,
        master_vend_name,
        seg_code
    """)


main()