# -*- coding: utf-8 -*-

from synnex.bigdata import conf
from synnex.bigdata.pyspark import run_sql

# dw_${country}.dws_disty_brpt_pl_extend_1d
# dw_${country}.dws_disty_brpt_bo_aging_df


def main():
    exec_sql()


def exec_sql():
    run_sql("""
    with
    table_dws as (
    select
        date_flag       ,
        cust_no         ,
        cust_name       ,
        mcust_no        ,
        mcust_name      ,
        cust_terr       ,
        terr_name       ,
        terr_sub_group  ,
        sub_group_desc  ,
        terr_group      ,
        terr_group_desc ,
        cust_type       ,
        cust_type_desc  ,
        division        ,
        division_desc   ,
        vpl_no	        ,
        vpl_code	    ,
        vpc_group_id	,
        vpc_group_desc	,
        vend_no	        ,
        vend_name	    ,
        master_vend_no	,
        master_vend_name,
        seg_code	    ,
        nvl(company_no,1) as company_no      ,
        pm_id,
        pm_mgr_id,
        pm_dir_id,
        pm_vp_id,
    
        sum(gross_sales) as gross_sales,
        sum(net_sales) as net_sales,
        sum(gross_cost) as gross_cost,
        sum(net_cost) as net_cost,
        sum(scm_usage) as scm_usage,
        sum(ds_sales) as ds_sales,
        sum(stock_sales) as stock_sales,
        sum(ds_cost) as ds_cost,
        sum(stock_cost) as stock_cost,
        sum(ds_scm_usage) as ds_scm_usage,
        sum(stock_scm_usage) as stock_scm_usage,
        sum(total_unit) as total_unit,
        sum(total_weight) as total_weight,
    
        sum(cgp) as cgp,
        sum(total_btl) as total_btl,
        sum(tgm_amt) as tgm_amt,
        sum(gm_amt) as gm_amt,
        sum(ngm_amt) as ngm_amt,
        sum(oplgm_amt) as oplgm_amt,
        sum(oplgm_plus_amt) as oplgm_plus_amt,
    
        sum(ap_finance) as ap_finance,
        sum(inv_cost) as inv_cost,
        sum(inv_reserve) as inv_reserve,
        sum(cr_risk_cterm) as cr_risk_cterm,
        sum(flr_synnex) as flr_synnex,
        sum(direct_credit) as direct_credit,
        sum(csgn_edi_fee) as csgn_edi_fee,
        sum(corporate) as corporate,
        sum(sfs) as sfs,
        sum(scm_risk) as scm_risk,
        sum(flr_vendor) as flr_vendor,
        sum(cust_finance_sales) as cust_finance_sales,
        sum(cust_pmt_disc) as cust_pmt_disc,
        sum(cvr_rm) as cvr_rm,
        sum(ar_fin_recovery) as ar_fin_recovery,
        sum(mfg_oh) as mfg_oh,
        sum(cust_finance) as cust_finance,
        sum(rma) as rma,
        sum(hc_sales) as hc_sales,
        sum(order_overhead) as order_overhead,
        sum(margin_share) as margin_share,
        sum(ap_adj) as ap_adj,
        sum(pdt) as pdt,
        sum(scm_cost) as scm_cost,
        sum(infrastructure) as infrastructure,
        sum(marketing) as marketing,
        sum(coop) as coop,
        sum(one_time_btl) as one_time_btl,
        sum(hbtl) as hbtl,
        sum(scm_profit_adj) as scm_profit_adj,
        sum(hc_pm) as hc_pm,
        sum(hc_bd) as hc_bd,
        sum(btl) as btl,
        sum(btl_sales) as btl_sales,
        sum(btl_backout) as btl_backout,
        sum(cust_rebate) as cust_rebate,
        sum(mof) as mof,
        sum(frt_out_load) as frt_out_load,
        sum(frt_out_exp) as frt_out_exp,
        sum(whoh_pack) as whoh_pack,
        sum(frt_ob_recovery) as frt_ob_recovery,
        sum(frt_ib_recovery) as frt_ib_recovery,
        sum(others) as others,
        sum(others_sales) as others_sales,
        sum(scm_disc) as scm_disc,
        sum(scm_ndisc) as scm_ndisc,
        sum(frt_in) as frt_in,
        sum(trans_btl) as trans_btl,
        sum(trans_btl_sales) as trans_btl_sales,
        
        SUM(bo_gross_sales) as bo_gross_sales,
        SUM(bo_gross_cost) as bo_gross_cost,
        SUM(bo_total_unit) as bo_total_unit,
        SUM(bo_gm_amt) as bo_gm_amt,
        SUM(so_gross_sales) as so_gross_sales,
        SUM(so_gross_cost) as so_gross_cost,
        SUM(so_total_unit) as so_total_unit,
        SUM(so_gm_amt) as so_gm_amt,
        SUM(bo_age0_7) as bo_age0_7,
        SUM(bo_age8_14) as bo_age8_14,
        SUM(bo_age15_21) as bo_age15_21,
        SUM(bo_age21_up) as bo_age21_up,
        SUM(so_age0_7) as so_age0_7,
        SUM(so_age8_14) as so_age8_14,
        SUM(so_age15_21) as so_age15_21,
        SUM(so_age21_up) as so_age21_up,
        sum(fx_cost) as fx_cost,
        sum(btl_sales_for_opl) as  btl_sales_for_opl ,       
		sum(trans_btl_sales_for_opl) as trans_btl_sales_for_opl,   
		sum(pdt_for_opl) as pdt_for_opl,               
		sum(cust_rebate_for_opl) as cust_rebate_for_opl,       
		sum(cvr_rm_for_opl) as cvr_rm_for_opl,            
		sum(btl_backout_for_opl) as btl_backout_for_opl,       
		sum(cust_pmt_disc_for_opl) as cust_pmt_disc_for_opl,     
		sum(cust_finance_sales_for_opl) as cust_finance_sales_for_opl,
		sum(rma_for_opl) as rma_for_opl,               
		sum(ar_fin_recovery_for_opl) as ar_fin_recovery_for_opl,   
		sum(order_overhead_for_opl) as order_overhead_for_opl,    
		sum(frt_out_exp_for_opl) as frt_out_exp_for_opl,       
		sum(frt_ob_recovery_for_opl) as frt_ob_recovery_for_opl
    from dw_${country}.dws_disty_brpt_pl_extend_1d
    where date_flag between '${firstday_of_month}' and '${date_flag}'
    group by
        pm_id,
        pm_mgr_id,
        pm_dir_id,
        pm_vp_id,
        date_flag       ,
        cust_no         ,
        cust_name       ,
        mcust_no        ,
        mcust_name      ,
        cust_terr       ,
        terr_name       ,
        terr_sub_group  ,
        sub_group_desc  ,
        terr_group      ,
        terr_group_desc ,
        cust_type       ,
        cust_type_desc  ,
        division        ,
        division_desc   ,
        vpl_no	        ,
        vpl_code	    ,
        vpc_group_id	,
        vpc_group_desc	,
        vend_no	        ,
        vend_name	    ,
        master_vend_no	,
        master_vend_name,
        seg_code	    ,
        nvl(company_no,1)      )
    
    insert overwrite table dw_${country}.dws_disty_brpt_cross_cvv_1d partition(date_flag)
    select
        table_dws.cust_no         ,
        table_dws.cust_name       ,
        table_dws.mcust_no        ,
        table_dws.mcust_name      ,
        table_dws.cust_terr       ,
        table_dws.terr_name       ,
        table_dws.terr_sub_group  ,
        table_dws.sub_group_desc  ,
        table_dws.terr_group      ,
        table_dws.terr_group_desc ,
        table_dws.cust_type       ,
        table_dws.cust_type_desc  ,
        table_dws.division        ,
        table_dws.division_desc   ,
        table_dws.vpl_no	      ,
        table_dws.vpl_code	      ,
        table_dws.vpc_group_id	  ,
        table_dws.vpc_group_desc  ,
        table_dws.vend_no	      ,
        table_dws.vend_name	      ,
        table_dws.master_vend_no  ,
        table_dws.master_vend_name,
        table_dws.seg_code	      ,
        table_dws.company_no      ,
    
        table_dws.gross_sales,
        table_dws.net_sales,
        table_dws.gross_cost,
        table_dws.net_cost,
        table_dws.scm_usage,
        table_dws.ds_sales,
        table_dws.stock_sales,
        table_dws.ds_cost,
        table_dws.stock_cost,
        table_dws.ds_scm_usage,
        table_dws.stock_scm_usage,
        table_dws.total_unit,
        table_dws.total_weight,
    
        table_dws.cgp,
        table_dws.total_btl,
        table_dws.tgm_amt,
        table_dws.gm_amt,
        table_dws.ngm_amt,
        table_dws.oplgm_amt,
    
        table_dws.bo_gross_sales,
        table_dws.bo_gross_cost,
        table_dws.bo_total_unit,
        table_dws.bo_gm_amt,
        table_dws.so_gross_sales,
        table_dws.so_gross_cost,
        table_dws.so_total_unit,
        table_dws.so_gm_amt,
        table_dws.bo_age0_7,
        table_dws.bo_age8_14,
        table_dws.bo_age15_21,
        table_dws.bo_age21_up,
        table_dws.so_age0_7,
        table_dws.so_age8_14,
        table_dws.so_age15_21,
        table_dws.so_age21_up,
    
        table_dws.ap_finance,
        table_dws.inv_cost,
        table_dws.inv_reserve,
        table_dws.cr_risk_cterm,
        table_dws.flr_synnex,
        table_dws.direct_credit,
        table_dws.csgn_edi_fee,
        table_dws.corporate,
        table_dws.sfs,
        table_dws.scm_risk,
        table_dws.flr_vendor,
        table_dws.cust_finance_sales,
        table_dws.cust_pmt_disc,
        table_dws.cvr_rm,
        table_dws.ar_fin_recovery,
        table_dws.mfg_oh,
        table_dws.cust_finance,
        table_dws.rma,
        table_dws.hc_sales,
        table_dws.order_overhead,
        table_dws.margin_share,
        table_dws.ap_adj,
        table_dws.pdt,
        table_dws.scm_cost,
        table_dws.infrastructure,
        table_dws.marketing,
        table_dws.coop,
        table_dws.one_time_btl,
        table_dws.hbtl,
        table_dws.scm_profit_adj,
        table_dws.hc_pm,
        table_dws.hc_bd,
        table_dws.btl,
        table_dws.btl_sales,
        table_dws.btl_backout,
        table_dws.cust_rebate,
        table_dws.mof,
        table_dws.frt_out_load,
        table_dws.frt_out_exp,
        table_dws.whoh_pack,
        table_dws.frt_ob_recovery,
        table_dws.frt_ib_recovery,
        table_dws.others,
        table_dws.others_sales,
        table_dws.scm_disc,
        table_dws.scm_ndisc,
        table_dws.frt_in,
        table_dws.trans_btl,
        table_dws.trans_btl_sales,
    
        '${etl_timestamp}',
        table_dws.pm_id,
        concat_ws(' ', table_manager.firstname, table_manager.lastname) as pm_name,
        table_dws.pm_mgr_id,
        concat_ws(' ', table_manager2.firstname, table_manager2.lastname) as pm_manager_name,
        table_dws.pm_dir_id,
        concat_ws(' ', table_manager3.firstname, table_manager3.lastname) as pm_director_name,
        table_dws.pm_vp_id,
        concat_ws(' ', table_manager4.firstname, table_manager4.lastname) as pm_vp_name,
        table_dws.fx_cost,
        table_dws.btl_sales_for_opl         ,
		table_dws.trans_btl_sales_for_opl   ,
		table_dws.pdt_for_opl               ,
		table_dws.cust_rebate_for_opl       ,
		table_dws.cvr_rm_for_opl            ,
		table_dws.btl_backout_for_opl       ,
		table_dws.cust_pmt_disc_for_opl     ,
		table_dws.cust_finance_sales_for_opl,
		table_dws.rma_for_opl               ,
		table_dws.ar_fin_recovery_for_opl   ,
		table_dws.order_overhead_for_opl    ,
		table_dws.frt_out_exp_for_opl       ,
		table_dws.frt_ob_recovery_for_opl   ,
        table_dws.oplgm_plus_amt,
        table_dws.date_flag
    from table_dws
    
    left join ods_${country}.ods_cis_corp_manager as table_manager   --unique id : userid
    on table_dws.pm_id = table_manager.userid
    left join ods_${country}.ods_cis_corp_manager as table_manager2   --unique id : userid
    on table_dws.pm_mgr_id = table_manager2.userid
    left join ods_${country}.ods_cis_corp_manager as table_manager3   --unique id : userid
    on table_dws.pm_dir_id = table_manager3.userid
    left join ods_${country}.ods_cis_corp_manager as table_manager4   --unique id : userid
    on table_dws.pm_vp_id = table_manager4.userid;
    """)


main()