# -*- coding: utf-8 -*-

from synnex.bigdata import conf
from synnex.bigdata.pyspark import run_sql

# dw_${country}.dws_disty_brpt_bd_1d


def main():
    exec_sql()


def exec_sql():
    run_sql("""
    insert overwrite table dw_${country}.dws_disty_brpt_bd_cust_1d partition(date_flag)
    select
        project_no,
        project_name,
        task_no,
        task_name,
        nvl(company_no,1) as company_no,
        cust_no,
        cust_name,
        mcust_no,
        mcust_name,
        cust_terr,
        terr_name,
        cust_type,
        cust_type_desc,
        division,
        division_desc,
        terr_sub_group,
        sub_group_desc,
        terr_group,
        terr_group_desc,
    
        sum(gross_sales) as gross_sales,
        sum(net_sales) as net_sales,
        sum(gross_cost) as gross_cost,
        sum(net_cost) as net_cost,
        sum(scm_usage) as scm_usage,
        sum(ds_sales) as ds_sales,
        sum(stock_sales) as stock_sales,
        sum(ds_cost) as ds_cost,
        sum(stock_cost) as stock_cost,
        sum(ds_scm_usage) as ds_scm_usage,
        sum(stock_scm_usage) as stock_scm_usage,
        sum(total_unit) as total_unit,
        sum(total_weight) as total_weight,
        sum(cgp) as cgp,
        sum(total_btl) as total_btl,
        sum(tgm_amt) as tgm_amt,
        sum(gm_amt) as gm_amt,
        sum(ngm_amt) as ngm_amt,
        sum(oplgm_amt) as oplgm_amt,
    
        SUM(bo_gross_sales) as bo_gross_sales,
        SUM(bo_gross_cost) as bo_gross_cost,
        SUM(bo_total_unit) as bo_total_unit,
        SUM(bo_gm_amt) as bo_gm_amt,
        SUM(so_gross_sales) as so_gross_sales,
        SUM(so_gross_cost) as so_gross_cost,
        SUM(so_total_unit) as so_total_unit,
        SUM(so_gm_amt) as so_gm_amt,
        SUM(bo_age0_7) as bo_age0_7,
        SUM(bo_age8_14) as bo_age8_14,
        SUM(bo_age15_21) as bo_age15_21,
        SUM(bo_age21_up) as bo_age21_up,
        SUM(so_age0_7) as so_age0_7,
        SUM(so_age8_14) as so_age8_14,
        SUM(so_age15_21) as so_age15_21,
        SUM(so_age21_up) as so_age21_up,
    
        sum(ap_finance) as ap_finance,
        sum(inv_cost) as inv_cost,
        sum(inv_reserve) as inv_reserve,
        sum(cr_risk_cterm) as cr_risk_cterm,
        sum(flr_synnex) as flr_synnex,
        sum(direct_credit) as direct_credit,
        sum(csgn_edi_fee) as csgn_edi_fee,
        sum(corporate) as corporate,
        sum(sfs) as sfs,
        sum(scm_risk) as scm_risk,
        sum(flr_vendor) as flr_vendor,
        sum(cust_finance_sales) as cust_finance_sales,
        sum(cust_pmt_disc) as cust_pmt_disc,
        sum(cvr_rm) as cvr_rm,
        sum(ar_fin_recovery) as ar_fin_recovery,
        sum(mfg_oh) as mfg_oh,
        sum(cust_finance) as cust_finance,
        sum(rma) as rma,
        sum(hc_sales) as hc_sales,
        sum(order_overhead) as order_overhead,
        sum(margin_share) as margin_share,
        sum(ap_adj) as ap_adj,
        sum(pdt) as pdt,
        sum(scm_cost) as scm_cost,
        sum(infrastructure) as infrastructure,
        sum(marketing) as marketing,
        sum(coop) as coop,
        sum(one_time_btl) as one_time_btl,
        sum(hbtl) as hbtl,
        sum(scm_profit_adj) as scm_profit_adj,
        sum(hc_pm) as hc_pm,
        sum(hc_bd) as hc_bd,
        sum(btl) as btl,
        sum(btl_sales) as btl_sales,
        sum(btl_backout) as btl_backout,
        sum(cust_rebate) as cust_rebate,
        sum(mof) as mof,
        sum(frt_out_load) as frt_out_load,
        sum(frt_out_exp) as frt_out_exp,
        sum(whoh_pack) as whoh_pack,
        sum(frt_ob_recovery) as frt_ob_recovery,
        sum(frt_ib_recovery) as frt_ib_recovery,
        sum(others) as others,
        sum(others_sales) as others_sales,
        sum(scm_disc) as scm_disc,
        sum(scm_ndisc) as scm_ndisc,
        sum(frt_in) as frt_in,
        sum(trans_btl) as trans_btl,
        sum(trans_btl_sales) as trans_btl_sales,
        '${etl_timestamp}',
        b33_flag,
        sum(fx_cost),
        sum(btl_sales_for_opl) as  btl_sales_for_opl ,       
		sum(trans_btl_sales_for_opl) as trans_btl_sales_for_opl,   
		sum(pdt_for_opl) as pdt_for_opl,               
		sum(cust_rebate_for_opl) as cust_rebate_for_opl,       
		sum(cvr_rm_for_opl) as cvr_rm_for_opl,            
		sum(btl_backout_for_opl) as btl_backout_for_opl,       
		sum(cust_pmt_disc_for_opl) as cust_pmt_disc_for_opl,     
		sum(cust_finance_sales_for_opl) as cust_finance_sales_for_opl,
		sum(rma_for_opl) as rma_for_opl,               
		sum(ar_fin_recovery_for_opl) as ar_fin_recovery_for_opl,   
		sum(order_overhead_for_opl) as order_overhead_for_opl,    
		sum(frt_out_exp_for_opl) as frt_out_exp_for_opl,       
		sum(frt_ob_recovery_for_opl) as frt_ob_recovery_for_opl,  
		
		sum(oplgm_plus_amt) as oplgm_plus_amt,
        date_flag
    from dw_${country}.dws_disty_brpt_bd_1d
    where date_flag between '${firstday_of_month}' and '${date_flag}'
    group by
        date_flag,
        b33_flag,
        project_no,
        project_name,
        task_no,
        task_name,
        nvl(company_no,1),
        cust_no,
        cust_name,
        mcust_no,
        mcust_name,
        cust_terr,
        terr_name,
        cust_type,
        cust_type_desc,
        division,
        division_desc,
        terr_sub_group,
        sub_group_desc,
        terr_group,
        terr_group_desc ;
    """)


main()