# -*- coding: utf-8 -*-
# @Time : 3/29/2024 4:31 PM
# @Author : Marvin Ma

from synnex.bigdata import conf
from synnex.bigdata.pyspark import run_sql


def main():

    run_sql("""
    insert overwrite table dw_${country}.dws_disty_brpt_pl_extend_wtd partition(dt_week)
    select
        table_dim.w as week_no,
        table_dim.max_date_flag as date_flag,

        nvl(table_left.cust_no,-3),
        table_left.cust_name,
        nvl(table_left.mcust_no,-3),
        table_left.mcust_name,
        nvl(table_left.cust_terr,-3),
        table_left.terr_name,
        nvl(table_left.cust_type,-3),
        table_left.cust_type_desc,
        nvl(table_left.division,-3),
        table_left.division_desc,
        nvl(table_left.terr_sub_group,-3),
        table_left.sub_group_desc,
        nvl(table_left.terr_group,-3),
        table_left.terr_group_desc,

        nvl(table_left.sales_rep_id,-3),
        nvl(table_left.sales_sup_id,-3),
        nvl(table_left.sales_mgr_id,-3),
        nvl(table_left.sales_dir_id,-3),
        nvl(table_left.sales_vp_id,-3),

        nvl(table_left.sku_no,-3),
        table_left.part_no,
        table_left.mfg_partno,
        nvl(table_left.vpl_no,-3),
        table_left.vpl_code,
        nvl(table_left.vpc_group_id,-3),
        table_left.vpc_group_desc,
        nvl(table_left.vend_no,-3),
        table_left.vend_name,
        nvl(table_left.master_vend_no,-3),
        table_left.master_vend_name,
        nvl(table_left.group_id,-3),
        table_left.seg_code,

        nvl(table_left.pm_id,-3),
        nvl(table_left.pm_mgr_id,-3),
        nvl(table_left.pm_dir_id,-3),
        nvl(table_left.pm_vp_id,-3),
        nvl(table_left.buyer_id,-3),
        nvl(table_left.buyer_mgr_id,-3),
        nvl(table_left.buyer_dir_id,-3),
        nvl(table_left.buyer_vp_id,-3),

        nvl(table_left.company_no,1),

        nvl(sum(gross_sales),0),
        nvl(sum(net_sales),0),
        nvl(sum(gross_cost),0),
        nvl(sum(net_cost),0),
        nvl(sum(scm_usage),0),
        nvl(sum(ds_sales),0),
        nvl(sum(stock_sales),0),
        nvl(sum(ds_cost),0),
        nvl(sum(stock_cost),0),
        nvl(sum(ds_scm_usage),0),
        nvl(sum(stock_scm_usage),0),
        nvl(sum(total_unit),0),
        nvl(sum(total_weight),0),

        nvl(sum(cgp),0),
        nvl(sum(total_btl),0),
        nvl(sum(tgm_amt),0),
        nvl(sum(gm_amt),0),
        nvl(sum(ngm_amt),0),
        nvl(sum(oplgm_amt),0),

        nvl(sum(ap_finance),0),
        nvl(sum(inv_cost),0),
        nvl(sum(inv_reserve),0),
        nvl(sum(cr_risk_cterm),0),
        nvl(sum(flr_synnex),0),
        nvl(sum(direct_credit),0),
        nvl(sum(csgn_edi_fee),0),
        nvl(sum(corporate),0),
        nvl(sum(sfs),0),
        nvl(sum(scm_risk),0),
        nvl(sum(flr_vendor),0),
        nvl(sum(cust_finance_sales),0),
        nvl(sum(cust_pmt_disc),0),
        nvl(sum(cvr_rm),0),
        nvl(sum(ar_fin_recovery),0),
        nvl(sum(mfg_oh),0),
        nvl(sum(cust_finance),0),
        nvl(sum(rma),0),
        nvl(sum(hc_sales),0),
        nvl(sum(order_overhead),0),
        nvl(sum(margin_share),0),
        nvl(sum(ap_adj),0),
        nvl(sum(pdt),0),
        nvl(sum(scm_cost),0),
        nvl(sum(infrastructure),0),
        nvl(sum(marketing),0),
        nvl(sum(coop),0),
        nvl(sum(one_time_btl),0),
        nvl(sum(hbtl),0),
        nvl(sum(scm_profit_adj),0),
        nvl(sum(hc_pm),0),
        nvl(sum(hc_bd),0),
        nvl(sum(btl),0),
        nvl(sum(btl_sales),0),
        nvl(sum(btl_backout),0),
        nvl(sum(cust_rebate),0),
        nvl(sum(mof),0),
        nvl(sum(frt_out_load),0),
        nvl(sum(frt_out_exp),0),
        nvl(sum(whoh_pack),0),
        nvl(sum(frt_ob_recovery),0),
        nvl(sum(frt_ib_recovery),0),
        nvl(sum(others),0),
        nvl(sum(others_sales),0),
        nvl(sum(scm_disc),0),
        nvl(sum(scm_ndisc),0),
        nvl(sum(frt_in),0),
        nvl(sum(trans_btl),0),
        nvl(sum(trans_btl_sales),0),
        '${etl_timestamp}',
        nvl(sum(fx_cost),0),
        
        nvl(sum(btl_sales_for_opl	        ),0),
        nvl(sum(trans_btl_sales_for_opl	    ),0),
        nvl(sum(pdt_for_opl         	    ),0),
        nvl(sum(cust_rebate_for_opl	        ),0),
        nvl(sum(cvr_rm_for_opl	            ),0),
        nvl(sum(btl_backout_for_opl	        ),0),
        nvl(sum(cust_pmt_disc_for_opl	    ),0),
        nvl(sum(cust_finance_sales_for_opl	),0),
        nvl(sum(rma_for_opl             	),0),
        nvl(sum(ar_fin_recovery_for_opl 	),0),
        nvl(sum(order_overhead_for_opl  	),0),
        nvl(sum(frt_out_exp_for_opl     	),0),
        nvl(sum(frt_ob_recovery_for_opl 	),0),
        nvl(sum(oplgm_plus_amt              ),0),
        
        table_dim.week_flag
    from (select * from dw_${country}.dws_disty_brpt_pl_extend_1d
          where date_flag between '${week_begin_of_firstday}' and '${date_flag}') as table_left
    left join (select
               w,
               week_flag,
               date_flag,
               max(date_flag) over(partition by w,week_flag) as max_date_flag
               from dim_${country}.dim_pub_date
               where date_flag between '${week_begin_of_firstday}' and '${date_flag}') as table_dim
    on table_left.date_flag = table_dim.date_flag
    group by
        table_dim.w,
        table_dim.week_flag,
        table_dim.max_date_flag,
        table_left.cust_no,
        table_left.cust_name,
        table_left.mcust_no,
        table_left.mcust_name,
        table_left.cust_terr,
        table_left.terr_name,
        table_left.cust_type,
        table_left.cust_type_desc,
        table_left.division,
        table_left.division_desc,
        table_left.terr_sub_group,
        table_left.sub_group_desc,
        table_left.terr_group,
        table_left.terr_group_desc,
        table_left.sales_rep_id,
        table_left.sales_sup_id,
        table_left.sales_mgr_id,
        table_left.sales_dir_id,
        table_left.sales_vp_id,
        table_left.sku_no,
        table_left.part_no,
        table_left.mfg_partno,
        table_left.vpl_no,
        table_left.vpl_code,
        table_left.vpc_group_id,
        table_left.vpc_group_desc,
        table_left.vend_no,
        table_left.vend_name,
        table_left.master_vend_no,
        table_left.master_vend_name,
        table_left.group_id,
        table_left.seg_code,
        table_left.pm_id,
        table_left.pm_mgr_id,
        table_left.pm_dir_id,
        table_left.pm_vp_id,
        table_left.buyer_id,
        table_left.buyer_mgr_id,
        table_left.buyer_dir_id,
        table_left.buyer_vp_id,
        nvl(table_left.company_no,1)
    """)


main()