# -*- coding: utf-8 -*-
# @Time : 9/28/2023 10:10 AM
# @Author : Marvin Ma

from synnex.bigdata import conf
from synnex.bigdata.pyspark import run_sql


# dw_{country}.dws_disty_brpt_cust_type_comb_mtd


def main():
    country = conf.get("country")
    date_flag = conf.get("date_flag")  # date_flag = yesterday = @process_date
    dt_month = conf.get("dt_month")  # date_flag format to 'yyyy-MM'
    etl_timestamp = conf.get("etl_timestamp")

    exec_main_sql(country, date_flag, dt_month, etl_timestamp)


def exec_main_sql(country, date_flag, dt_month, etl_timestamp):
    run_sql("""
    with
    table_goal as (
    select
        division,
        company_no,
        sum(net_sales_local_currency)                     as goal_nsales,
        sum(gm * net_sales_local_currency / 100)          as goal_gm,
        sum(ngm * net_sales_local_currency / 100)         as goal_ngm,
        sum(oplgm * net_sales_local_currency / 100)       as goal_opl_gm,
        sum(tgm * net_sales_local_currency / 100)         as goal_tgm,
        null             as goal_dos,
        null             as goal_pdt,
        null             as goal_total_btl,
        sum(cust_cnt)    as goal_cust_cnt,
        sum(soft_local_currency)                          as goal_soft_sales,
        sum(opl_plus * net_sales_local_currency / 100)    as goal_oplgm_plus_amt
    from dw_${country}.dwd_disty_sales_report_goal_view  -- unique id：period,goal_type,division,cust_type,terr_group,terr_sub_group,cust_terr,cust_no,master_cust_no [when cust_terr is not null]
    where period = ${month_no} and goal_type = 'NORMAL'
    and cust_no = 0
    and cust_terr = 0
    and terr_sub_group = 0
    and terr_group = 0
    and cust_type = 0
    and division <> 0
    group by
        division,
        company_no
    having goal_nsales <> 0
    or goal_cust_cnt <> 0
    or goal_soft_sales <> 0),
    
    table_dws as (
    select 
        division       ,
        nvl(company_no,1) as company_no     ,

        sum(d_sales             ) as d_sales       ,
        sum(d_cost              ) as d_cost        ,
        sum(d_unit              ) as d_unit        ,
        sum(d_gm                ) as d_gm          ,
        sum(d_ngm               ) as d_ngm         ,
        sum(d_opl               ) as d_opl         ,
        sum(d_scm_usage         ) as d_scm_usage   ,
        sum(d_tgm               ) as d_tgm         ,
        sum(d_cgp               ) as d_cgp         ,
        sum(d_total_btl         ) as d_total_btl   ,

        sum(w_sales             ) as w_sales      ,
        sum(w_cost              ) as w_cost       ,
        sum(w_unit              ) as w_unit       ,
        sum(w_gm                ) as w_gm         ,
        sum(w_ngm               ) as w_ngm        ,
        sum(w_opl               ) as w_opl        ,
        sum(w_scm_usage         ) as w_scm_usage  ,
        sum(w_tgm               ) as w_tgm        ,
        sum(w_cgp               ) as w_cgp        ,
        sum(w_total_btl         ) as w_total_btl  ,

        sum(m_sales             ) as m_sales           ,
        sum(m_cost              ) as m_cost            ,
        sum(m_unit              ) as m_unit            ,
        sum(m_gm                ) as m_gm              ,
        sum(m_ngm               ) as m_ngm             ,
        sum(m_opl               ) as m_opl             ,
        sum(m_scm_usage         ) as m_scm_usage       ,
        sum(m_tgm               ) as m_tgm             ,
        sum(m_scm_disc          ) as m_scm_disc        ,
        sum(m_scm_ndisc         ) as m_scm_ndisc       ,
        sum(m_ds_sales          ) as m_ds_sales        ,
        sum(m_stock_sales       ) as m_stock_sales     ,
        sum(m_ds_cost           ) as m_ds_cost         ,
        sum(m_stock_cost        ) as m_stock_cost      ,
        sum(m_ds_scm_usage      ) as m_ds_scm_usage    ,
        sum(m_stock_scm_usage   ) as m_stock_scm_usage ,
        sum(m_cgp               ) as m_cgp             ,
        sum(m_total_btl         ) as m_total_btl       ,

        sum(pm_sales            ) as pm_sales          ,
        sum(pm_cost             ) as pm_cost           ,
        sum(pm_unit             ) as pm_unit           ,
        sum(pm_gm               ) as pm_gm             ,
        sum(pm_ngm              ) as pm_ngm            ,
        sum(pm_opl              ) as pm_opl            ,
        sum(pm_scm_usage        ) as pm_scm_usage      ,
        sum(pm_tgm              ) as pm_tgm            ,
        sum(pm_scm_disc         ) as pm_scm_disc       ,
        sum(pm_scm_ndisc        ) as pm_scm_ndisc      ,
        sum(pm_ds_sales         ) as pm_ds_sales       ,
        sum(pm_stock_sales      ) as pm_stock_sales    ,
        sum(pm_ds_cost          ) as pm_ds_cost        ,
        sum(pm_stock_cost       ) as pm_stock_cost     ,
        sum(pm_ds_scm_usage     ) as pm_ds_scm_usage   ,
        sum(pm_stock_scm_usage  ) as pm_stock_scm_usage,
        sum(pm_cgp              ) as pm_cgp            ,
        sum(pm_total_btl        ) as pm_total_btl      ,

        sum(ppm_sales           ) as ppm_sales          ,
        sum(ppm_cost            ) as ppm_cost           ,
        sum(ppm_unit            ) as ppm_unit           ,
        sum(ppm_gm              ) as ppm_gm             ,
        sum(ppm_ngm             ) as ppm_ngm            ,
        sum(ppm_opl             ) as ppm_opl            ,
        sum(ppm_scm_usage       ) as ppm_scm_usage      ,
        sum(ppm_tgm             ) as ppm_tgm            ,
        sum(ppm_scm_disc        ) as ppm_scm_disc       ,
        sum(ppm_scm_ndisc       ) as ppm_scm_ndisc      ,
        sum(ppm_ds_sales        ) as ppm_ds_sales       ,
        sum(ppm_stock_sales     ) as ppm_stock_sales    ,
        sum(ppm_ds_cost         ) as ppm_ds_cost        ,
        sum(ppm_stock_cost      ) as ppm_stock_cost     ,
        sum(ppm_ds_scm_usage    ) as ppm_ds_scm_usage   ,
        sum(ppm_stock_scm_usage ) as ppm_stock_scm_usage,
        sum(ppm_cgp             ) as ppm_cgp            ,
        sum(ppm_total_btl       ) as ppm_total_btl      ,

        sum(lm_sales            ) as lm_sales          ,
        sum(lm_cost             ) as lm_cost           ,
        sum(lm_unit             ) as lm_unit           ,
        sum(lm_gm               ) as lm_gm             ,
        sum(lm_ngm              ) as lm_ngm            ,
        sum(lm_opl              ) as lm_opl            ,
        sum(lm_scm_usage        ) as lm_scm_usage      ,
        sum(lm_tgm              ) as lm_tgm            ,
        sum(lm_scm_disc         ) as lm_scm_disc       ,
        sum(lm_scm_ndisc        ) as lm_scm_ndisc      ,
        sum(lm_ds_sales         ) as lm_ds_sales       ,
        sum(lm_stock_sales      ) as lm_stock_sales    ,
        sum(lm_ds_cost          ) as lm_ds_cost        ,
        sum(lm_stock_cost       ) as lm_stock_cost     ,
        sum(lm_ds_scm_usage     ) as lm_ds_scm_usage   ,
        sum(lm_stock_scm_usage  ) as lm_stock_scm_usage,
        sum(lm_cgp              ) as lm_cgp            ,
        sum(lm_total_btl        ) as lm_total_btl      ,

        sum(bo_gross_sales      ) as bo_gross_sales   ,
        sum(bo_gross_cost       ) as bo_gross_cost    ,
        sum(bo_total_unit       ) as bo_total_unit    ,
        sum(bo_gm_amt           ) as bo_gm_amt        ,
        sum(so_gross_sales      ) as so_gross_sales   ,
        sum(so_gross_cost       ) as so_gross_cost    ,
        sum(so_total_unit       ) as so_total_unit    ,
        sum(so_gm_amt           ) as so_gm_amt        ,
        sum(bo_age0_7           ) as bo_age0_7        ,
        sum(bo_age8_14          ) as bo_age8_14       ,
        sum(bo_age15_21         ) as bo_age15_21      ,
        sum(bo_age21_up         ) as bo_age21_up      ,
        sum(so_age0_7           ) as so_age0_7        ,
        sum(so_age8_14          ) as so_age8_14       ,
        sum(so_age15_21         ) as so_age15_21      ,
        sum(so_age21_up         ) as so_age21_up      ,

        sum(rr_unit             ) as rr_unit        ,
        sum(rr_sales            ) as rr_sales       ,
        sum(rr_cost             ) as rr_cost        ,
        sum(rr_gm               ) as rr_gm          ,
        sum(rr_ngm              ) as rr_ngm         ,
        sum(rr_opl              ) as rr_opl         ,
        sum(rr_cgp              ) as rr_cgp         ,
        sum(rr_total_btl        ) as rr_total_btl   ,
        sum(rr_tgm              ) as rr_tgm         ,
        sum(d_fx_cost) as d_fx_cost,
        sum(w_fx_cost) as w_fx_cost,
        sum(m_fx_cost) as m_fx_cost,
        sum(pm_fx_cost) as pm_fx_cost,
        sum(ppm_fx_cost) as ppm_fx_cost,
        sum(lm_fx_cost) as lm_fx_cost,
        sum(d_oplgm_plus_amt   ) as d_oplgm_plus_amt   ,
        sum(w_oplgm_plus_amt   ) as w_oplgm_plus_amt   ,
        sum(m_oplgm_plus_amt   ) as m_oplgm_plus_amt   ,
        sum(pm_oplgm_plus_amt  ) as pm_oplgm_plus_amt  ,
        sum(ppm_oplgm_plus_amt ) as ppm_oplgm_plus_amt ,
        sum(lm_oplgm_plus_amt  ) as lm_oplgm_plus_amt  ,
        sum(rr_oplgm_plus_amt  ) as rr_oplgm_plus_amt  
    from dw_${country}.dws_disty_brpt_cust_type_comb_mtd
    where date_flag = '${date_flag}'
    group by
        division       ,
        nvl(company_no,1) )
    
    insert overwrite table dw_${country}.dws_disty_brpt_division_comb_mtd partition(date_flag = '${date_flag}')
    select
        ${month_no},
        coalesce(table_dws.division,table_goal.division,-3),
        table_div.division_desc,
        coalesce(table_dws.company_no,table_goal.company_no) as company_no,
        nvl(table_dws.d_sales,0),
        nvl(table_dws.d_cost,0),
        nvl(table_dws.d_unit,0),
        nvl(table_dws.d_gm,0),
        nvl(table_dws.d_ngm,0),
        nvl(table_dws.d_opl,0),
        nvl(table_dws.d_scm_usage,0),
        nvl(table_dws.d_tgm,0),
        nvl(table_dws.d_cgp,0),
        nvl(table_dws.d_total_btl,0),
        nvl(table_dws.w_sales,0),
        nvl(table_dws.w_cost,0),
        nvl(table_dws.w_unit,0),
        nvl(table_dws.w_gm,0),
        nvl(table_dws.w_ngm,0),
        nvl(table_dws.w_opl,0),
        nvl(table_dws.w_scm_usage,0),
        nvl(table_dws.w_tgm,0),
        nvl(table_dws.w_cgp,0),
        nvl(table_dws.w_total_btl,0),
        nvl(table_dws.m_sales,0),
        nvl(table_dws.m_cost,0),
        nvl(table_dws.m_unit,0),
        nvl(table_dws.m_gm,0),
        nvl(table_dws.m_ngm,0),
        nvl(table_dws.m_opl,0),
        nvl(table_dws.m_scm_usage,0),
        nvl(table_dws.m_tgm,0),
        nvl(table_dws.m_scm_disc,0),
        nvl(table_dws.m_scm_ndisc,0),
        nvl(table_dws.m_ds_sales,0),
        nvl(table_dws.m_stock_sales,0),
        nvl(table_dws.m_ds_cost,0),
        nvl(table_dws.m_stock_cost,0),
        nvl(table_dws.m_ds_scm_usage,0),
        nvl(table_dws.m_stock_scm_usage,0),
        nvl(table_dws.m_cgp,0),
        nvl(table_dws.m_total_btl,0),
        nvl(table_dws.pm_sales,0),
        nvl(table_dws.pm_cost,0),
        nvl(table_dws.pm_unit,0),
        nvl(table_dws.pm_gm,0),
        nvl(table_dws.pm_ngm,0),
        nvl(table_dws.pm_opl,0),
        nvl(table_dws.pm_scm_usage,0),
        nvl(table_dws.pm_tgm,0),
        nvl(table_dws.pm_scm_disc,0),
        nvl(table_dws.pm_scm_ndisc,0),
        nvl(table_dws.pm_ds_sales,0),
        nvl(table_dws.pm_stock_sales,0),
        nvl(table_dws.pm_ds_cost,0),
        nvl(table_dws.pm_stock_cost,0),
        nvl(table_dws.pm_ds_scm_usage,0),
        nvl(table_dws.pm_stock_scm_usage,0),
        nvl(table_dws.pm_cgp,0),
        nvl(table_dws.pm_total_btl,0),
        nvl(table_dws.ppm_sales,0),
        nvl(table_dws.ppm_cost,0),
        nvl(table_dws.ppm_unit,0),
        nvl(table_dws.ppm_gm,0),
        nvl(table_dws.ppm_ngm,0),
        nvl(table_dws.ppm_opl,0),
        nvl(table_dws.ppm_scm_usage,0),
        nvl(table_dws.ppm_tgm,0),
        nvl(table_dws.ppm_scm_disc,0),
        nvl(table_dws.ppm_scm_ndisc,0),
        nvl(table_dws.ppm_ds_sales,0),
        nvl(table_dws.ppm_stock_sales,0),
        nvl(table_dws.ppm_ds_cost,0),
        nvl(table_dws.ppm_stock_cost,0),
        nvl(table_dws.ppm_ds_scm_usage,0),
        nvl(table_dws.ppm_stock_scm_usage,0),
        nvl(table_dws.ppm_cgp,0),
        nvl(table_dws.ppm_total_btl,0),
        nvl(table_dws.lm_sales,0),
        nvl(table_dws.lm_cost,0),
        nvl(table_dws.lm_unit,0),
        nvl(table_dws.lm_gm,0),
        nvl(table_dws.lm_ngm,0),
        nvl(table_dws.lm_opl,0),
        nvl(table_dws.lm_scm_usage,0),
        nvl(table_dws.lm_tgm,0),
        nvl(table_dws.lm_scm_disc,0),
        nvl(table_dws.lm_scm_ndisc,0),
        nvl(table_dws.lm_ds_sales,0),
        nvl(table_dws.lm_stock_sales,0),
        nvl(table_dws.lm_ds_cost,0),
        nvl(table_dws.lm_stock_cost,0),
        nvl(table_dws.lm_ds_scm_usage,0),
        nvl(table_dws.lm_stock_scm_usage,0),
        nvl(table_dws.lm_cgp,0),
        nvl(table_dws.lm_total_btl,0),
        nvl(table_dws.bo_gross_sales,0),
        nvl(table_dws.bo_gross_cost,0),
        nvl(table_dws.bo_total_unit,0),
        nvl(table_dws.bo_gm_amt,0),
        nvl(table_dws.so_gross_sales,0),
        nvl(table_dws.so_gross_cost,0),
        nvl(table_dws.so_total_unit,0),
        nvl(table_dws.so_gm_amt,0),
        nvl(table_dws.bo_age0_7,0),
        nvl(table_dws.bo_age8_14,0),
        nvl(table_dws.bo_age15_21,0),
        nvl(table_dws.bo_age21_up,0),
        nvl(table_dws.so_age0_7,0),
        nvl(table_dws.so_age8_14,0),
        nvl(table_dws.so_age15_21,0),
        nvl(table_dws.so_age21_up,0),
        nvl(table_dws.rr_unit,0),
        nvl(table_dws.rr_sales,0),
        nvl(table_dws.rr_cost,0),
        nvl(table_dws.rr_gm,0),
        nvl(table_dws.rr_ngm,0),
        nvl(table_dws.rr_opl,0),
        nvl(table_dws.rr_cgp,0),
        nvl(table_dws.rr_total_btl,0),
        nvl(table_dws.rr_tgm,0),
        '${etl_timestamp}',
        nvl(table_goal.goal_nsales,0),
        nvl(table_goal.goal_gm,0),
        nvl(table_goal.goal_ngm,0),
        nvl(table_goal.goal_opl_gm,0),
        nvl(table_goal.goal_tgm,0),
        nvl(table_goal.goal_dos,0),
        nvl(table_goal.goal_pdt,0),
        nvl(table_goal.goal_total_btl,0),
        nvl(table_goal.goal_cust_cnt,0),
        nvl(table_dws.d_fx_cost,0),
        nvl(table_dws.w_fx_cost,0),
        nvl(table_dws.m_fx_cost,0),
        nvl(table_dws.pm_fx_cost,0),
        nvl(table_dws.ppm_fx_cost,0),
        nvl(table_dws.lm_fx_cost,0),
        nvl(table_goal.goal_soft_sales,0),
        nvl(table_dws.d_oplgm_plus_amt   ,0),
        nvl(table_dws.w_oplgm_plus_amt   ,0),
        nvl(table_dws.m_oplgm_plus_amt   ,0),
        nvl(table_dws.pm_oplgm_plus_amt  ,0),
        nvl(table_dws.ppm_oplgm_plus_amt ,0),
        nvl(table_dws.lm_oplgm_plus_amt  ,0),
        nvl(table_dws.rr_oplgm_plus_amt  ,0),
        nvl(table_goal.goal_oplgm_plus_amt,0)
    from table_dws
    full join table_goal
    on table_dws.division = table_goal.division
    and (table_dws.company_no = table_goal.company_no or table_goal.company_no = -1)
    
    left join ods_${country}.ods_cis_corp_division as table_div
    on nvl(table_dws.division,table_goal.division) = table_div.division
    """)


main()